2 files are added: test_saganovich.py __init__.py
alexander-sidorov/tms-qap05 pull request #10
Opened 2021-12-10 19:28 UTC by maryiasa

2021-12-10 21:25 UTC, alexander-sidorov requested changes
очень хорошо!

только один момент попрошу поправить.

Прошу назвать пулл-реквест так:

<Имя> <Фамилия> - Lesson 01

имя и фамилия латиницей

скобки `<` и `>` означают обязательность

2021-12-11 08:53 UTC, maryiasa commented
> очень хорошо!
> 
> только один момент попрошу поправить.
> 
> Прошу назвать пулл-реквест так:
> 
> <Имя> <Фамилия> - Lesson 01
> 
> имя и фамилия латиницей
> 
> скобки `<` и `>` означают обязательность

FIXED

2021-12-11 09:16 UTC, Tatsikuk26 approved these changes

2021-12-11 09:56 UTC, lerkin011 approved these changes

2021-12-12 21:06 UTC, vadison90125 approved these changes

2021-12-13 16:12 UTC, alexander-sidorov approved these changes
👍🏻👍🏻

2021-12-13 16:14 UTC, merged