Andrei bondar - Lesson 5
alexander-sidorov/tms-qap05 pull request #105
Opened 2021-12-24 18:15 UTC by Andrei9325

2021-12-25 12:46 UTC, alexander-sidorov approved these changes
тесты пофиксить и всё гуд

2021-12-25 13:49 UTC, alexander-sidorov requested changes

2021-12-25 13:49 UTC, alexander-sidorov commented on hw/andrei_bondar/test_aggress.py
> +    assert aggression(True) == "оно и видно!"
тест нужно починить)

**ожидание** в тесте и **реальность** в логике не совпадают)

2021-12-26 19:38 UTC, alexander-sidorov approved these changes

2021-12-26 19:44 UTC, maryiasa approved these changes

2021-12-26 22:39 UTC, YaroslavBelaychuk approved these changes

2021-12-27 10:10 UTC, merged