Maria Saganovich - Lesson05 homework
alexander-sidorov/tms-qap05 pull request #109
Opened 2021-12-27 16:38 UTC by maryiasa

2021-12-28 10:49 UTC, alexander-sidorov requested changes

2021-12-28 10:49 UTC, alexander-sidorov commented on hw/maria_saganovich/lesson5/task1.py
> +    first_last = operator.itemgetter(0, -1)
А есть ли оператор для такого действия, а не функция из модуля "operator"?

2021-12-28 10:49 UTC, alexander-sidorov commented on hw/maria_saganovich/lesson5/task2.py
> +    return " ".join([string_spl[i] for i in my_order])
А если без "for"?

2021-12-28 10:49 UTC, alexander-sidorov commented on hw/maria_saganovich/lesson5/task4.py
> +    return some_string2.join(ss1)
Если операнды поменять местами, то список выше будет не нужен

2021-12-28 18:44 UTC, maryiasa commented on hw/maria_saganovich/lesson5/task1.py
> +    first_last = operator.itemgetter(0, -1)
done

2021-12-28 18:44 UTC, maryiasa commented on hw/maria_saganovich/lesson5/task2.py
> +    return " ".join([string_spl[i] for i in my_order])
done

2021-12-28 18:44 UTC, maryiasa commented on hw/maria_saganovich/lesson5/task4.py
> +    return some_string2.join(ss1)
done

2021-12-28 19:25 UTC, alexander-sidorov requested changes

2021-12-28 19:25 UTC, alexander-sidorov commented on hw/maria_saganovich/lesson5/task4.py
> +    for char in some_string:
Давай попробуем переформулировать эту логику без инструкции `for`, используя только функционал строки

2021-12-28 19:25 UTC, alexander-sidorov commented on hw/maria_saganovich/lesson5/test_task4.py
> +    assert func4(some_string, some_string1) == "xoxoxoxo"
Крайней `o` быть не должно) хо

2021-12-29 07:39 UTC, maryiasa commented on hw/maria_saganovich/lesson5/test_task4.py
> +    assert func4(some_string, some_string1) == "xoxoxoxo"
fixed

2021-12-29 07:40 UTC, maryiasa commented on hw/maria_saganovich/lesson5/task4.py
> +    for char in some_string:
done

2021-12-29 08:14 UTC, alexander-sidorov approved these changes

2021-12-29 12:23 UTC, YaroslavBelaychuk approved these changes

2021-12-29 12:23 UTC, vadison90125 approved these changes

2021-12-29 12:27 UTC, merged