Sasha Yaroshevich - Lesson 05
alexander-sidorov/tms-qap05 pull request #110
Opened 2021-12-27 18:16 UTC by SashaYaroshevich

2021-12-28 10:46 UTC, alexander-sidorov requested changes

2021-12-28 10:46 UTC, alexander-sidorov commented on hw/sasha_yaroshevich/home_5_1.py
> +    a = stroka_two_words.split(',')
Слова вроде разделяются пробелом?

2021-12-28 10:46 UTC, alexander-sidorov commented on hw/sasha_yaroshevich/home_5_1.py
> +    return sort_coll[0:sort_coll.index(p2)]
Не будет работать по заданию

2021-12-28 10:46 UTC, alexander-sidorov commented on hw/sasha_yaroshevich/home_5_1.py
> +
Ошибка синтаксиса

2021-12-28 10:46 UTC, alexander-sidorov commented on hw/sasha_yaroshevich/home_5_1.py
> +    s = 'stroka_one'.join(new)
Не будет работать

2021-12-28 19:22 UTC, alexander-sidorov approved these changes

2021-12-28 21:04 UTC, Tatsikuk26 approved these changes

2021-12-28 21:06 UTC, Tobkirill approved these changes

2021-12-28 21:37 UTC, vadison90125 approved these changes

2021-12-29 10:57 UTC, alexander-sidorov requested changes

2021-12-29 10:57 UTC, alexander-sidorov commented on hw/sasha_yaroshevich/test_home5.py
> +    assert fu(fu_1, fu_2) == "a2b2c2d2e2f2"
в конце результата не должно быть объединяющего символа

2021-12-29 19:51 UTC, alexander-sidorov requested changes

2021-12-29 19:51 UTC, alexander-sidorov commented on hw/sasha_yaroshevich/home_5_1.py
> +    new_stroka = list(stroka)
давай уберём лишнюю конверсию

2022-01-02 20:21 UTC, SashaYaroshevich commented on hw/sasha_yaroshevich/home_5_1.py
> +    new_stroka = list(stroka)
corrected

2022-01-03 16:33 UTC, alexander-sidorov requested changes

2022-01-03 16:33 UTC, alexander-sidorov commented on hw/sasha_yaroshevich/test_home5.py
> +    assert fun(fun_1, fun_2) == [1, 2, 3, 4, 5]
пожалуйста, протестируй ещё дополнительно вот так:

```python
assert fun("abcdef", "d") == "abcd"
```

2022-01-03 17:32 UTC, SashaYaroshevich commented on hw/sasha_yaroshevich/test_home5.py
> +    assert fun(fun_1, fun_2) == [1, 2, 3, 4, 5]
тоже работает, но падали тесты, поменяли тип на Any тоже

2022-01-03 21:31 UTC, alexander-sidorov commented on hw/sasha_yaroshevich/test_home5.py
> +    assert fun(fun_1, fun_2) == [1, 2, 3, 4, 5]
> но падали тесты

потому и предложил дополнительный тест — увидел, что аннотация неподходящая)

2022-01-03 21:31 UTC, alexander-sidorov approved these changes

2022-01-05 15:44 UTC, Tatsikuk26 approved these changes

2022-01-05 15:50 UTC, vadison90125 approved these changes

2022-01-05 15:51 UTC, merged