Siarhei Apanel - Lesson 05 HW
alexander-sidorov/tms-qap05 pull request #111
Opened 2021-12-27 19:10 UTC by APOSHAml

2021-12-28 10:44 UTC, alexander-sidorov requested changes

2021-12-28 10:44 UTC, alexander-sidorov commented on hw/siarhei_apanel/test.py
> +    assert stroki("a4N67;i", "V") == "aV4VNV6V7V;ViV"
Последней "V" не должно быть

2021-12-28 10:44 UTC, alexander-sidorov commented on hw/siarhei_apanel/test.py
> +        == "D o   o n l y   w h a t   o n l y   y o u   c a n   d o"
Неправда, между буквами нет пробелов

2021-12-28 21:29 UTC, alexander-sidorov approved these changes

2021-12-28 21:36 UTC, vadison90125 approved these changes

2021-12-29 00:35 UTC, YaroslavBelaychuk approved these changes

2021-12-29 07:51 UTC, merged