Maksim Ptitski - Lesson 05 hw
alexander-sidorov/tms-qap05 pull request #112
Opened 2021-12-27 21:26 UTC by MaksimPtitski

2021-12-27 21:32 UTC, YaroslavBelaychuk approved these changes

2021-12-27 22:07 UTC, Zyola approved these changes

2021-12-28 10:41 UTC, alexander-sidorov requested changes

2021-12-28 10:41 UTC, alexander-sidorov commented on hw/maksim_ptitski/lesson5_hw.py
> +    for i in string_1:
Это работает, но "инструкцию for мы не проходили", поэтому предлагаю переписать весь блок с использованием функционала строки. Займет 1 строчку)

2021-12-28 19:20 UTC, alexander-sidorov requested changes

2021-12-28 19:20 UTC, alexander-sidorov commented on hw/maksim_ptitski/test_lesson5_hw.py
> +        == "Moaokosoiomo oPotoiotosokoio"  # noqa: W503
На конце не должно быть символа `o`

2021-12-28 21:28 UTC, alexander-sidorov approved these changes

2021-12-28 21:30 UTC, YaroslavBelaychuk approved these changes

2021-12-28 21:35 UTC, vadison90125 approved these changes

2021-12-29 07:48 UTC, APOSHAml approved these changes

2021-12-29 08:22 UTC, merged