Tatsiana Kukharskaya - Lesson 05
alexander-sidorov/tms-qap05 pull request #113
Opened 2021-12-28 06:34 UTC by Tatsikuk26

2021-12-28 10:39 UTC, alexander-sidorov requested changes

2021-12-28 10:39 UTC, alexander-sidorov commented on hw/tatsiana_kukharskaya/hw_lesson5.py
> +    f = working(me)
Что такое "working"?)

2021-12-28 10:39 UTC, alexander-sidorov commented on hw/tatsiana_kukharskaya/hw_lesson5.py
> +    nechto1 = nechto(None, nejki.index(nejki2) + 1)
Что такое "nechto"?)

2021-12-28 10:39 UTC, alexander-sidorov commented on hw/tatsiana_kukharskaya/hw_lesson5.py
> +    for a in string_1:
Пойдёт, но учитывая "инструкцию for мы не проходили, предлагаю заменит этот блок одной строчкой, без for. Подсказка: любая строка это умеет

2021-12-28 10:50 UTC, alexander-sidorov requested changes

2021-12-28 10:50 UTC, alexander-sidorov commented on hw/tatsiana_kukharskaya/hw_lesson5.py
> +    working = operator.itemgetter(0, -1)
А есть ли соответствующий оператор, а не функция из модуля "operator"?

2021-12-28 11:19 UTC, Tatsikuk26 commented on hw/tatsiana_kukharskaya/hw_lesson5.py
> +    f = working(me)
переменная, содержащая оператора, который преобразует эту переменную в вызываемый объект, который сможет принимать данные в виде списка например и будет извлекать то, что укажем, я так поняла) я думала вы на уроке его взяли, почитала и как поняла, так сделала)

2021-12-28 11:58 UTC, Tatsikuk26 commented on hw/tatsiana_kukharskaya/hw_lesson5.py
> +    working = operator.itemgetter(0, -1)
я читала что можно просто return me[0,2], где me это список, а 0 и 2 это индексы тех элементов, которые надо вывести

2021-12-28 15:33 UTC, alexander-sidorov commented on hw/tatsiana_kukharskaya/hw_lesson5.py
> +    f = working(me)
а, всё)) увидел, сорри. Так а как насчёт настоящего оператора, а не функции?

2021-12-28 15:34 UTC, alexander-sidorov commented on hw/tatsiana_kukharskaya/hw_lesson5.py
> +    working = operator.itemgetter(0, -1)
всё правильно, только скобки квадратные, а не круглые, и лучше не `2`, а `-1` :)

2021-12-28 15:36 UTC, alexander-sidorov commented on hw/tatsiana_kukharskaya/hw_lesson5.py
> +    working = operator.itemgetter(0, -1)
мне нравится вариант оставить оба решения (2 функции) и в тесте проверить, что они работают одинаково

2021-12-29 07:15 UTC, Tatsikuk26 commented on hw/tatsiana_kukharskaya/hw_lesson5.py
> +    nechto1 = nechto(None, nejki.index(nejki2) + 1)
исправиль положение :)

2021-12-29 07:32 UTC, alexander-sidorov requested changes

2021-12-29 07:32 UTC, alexander-sidorov commented on hw/tatsiana_kukharskaya/test_lesson5.py
> +        == "Taatasaiana Vasasaeasa"  # noqa: W503
На конце не должно быть символа-обьединителя

2021-12-29 07:49 UTC, Tatsikuk26 commented on hw/tatsiana_kukharskaya/test_lesson5.py
> +        == "Taatasaiana Vasasaeasa"  # noqa: W503
убрала

2021-12-29 07:50 UTC, Tatsikuk26 commented on hw/tatsiana_kukharskaya/test_lesson5.py
> +        == "Taatasaiana Vasasaeasa"  # noqa: W503
выглядит хуже

2021-12-29 08:10 UTC, alexander-sidorov requested changes

2021-12-29 08:10 UTC, alexander-sidorov commented on hw/tatsiana_kukharskaya/test_lesson5.py
> +    assert just_do_it4(string_for_test, char_for_test) == "Taatasaiana Vasasaeasa"  # noqa: W503
В конце строки-результата не должно быть символа-соединителя

2021-12-29 10:54 UTC, alexander-sidorov requested changes

2021-12-29 10:54 UTC, alexander-sidorov commented on hw/tatsiana_kukharskaya/test_lesson5.py
> +        == "Taaatasaiana aVasasaeasa"  # noqa: W503
в конце результата не должно быть символа-соединителя

2021-12-29 10:54 UTC, alexander-sidorov commented on hw/tatsiana_kukharskaya/test_lesson5.py
> +    for_test = "Do YoU like apple ?"  # noqa: E501
а зачем тут `# noqa: E501` ?

2021-12-29 10:54 UTC, alexander-sidorov commented on hw/tatsiana_kukharskaya/test_lesson5.py
> +    assert just_do_it5(for_test) == "Do You Like Apple ?"  # noqa: E501,W503
а тут зачем отключать E501 и W503?

2021-12-29 11:30 UTC, Tatsikuk26 commented on hw/tatsiana_kukharskaya/test_lesson5.py
> +    assert just_do_it5(for_test) == "Do You Like Apple ?"  # noqa: E501,W503
мне кажется там выскакивало что-то у меня такое?, могу сейчас убрать попробовать без них

2021-12-29 11:31 UTC, Tatsikuk26 commented on hw/tatsiana_kukharskaya/test_lesson5.py
> +        == "Taaatasaiana aVasasaeasa"  # noqa: W503
это не я так форматирую, это блацк так хочет насколько я понимаю

2021-12-29 11:36 UTC, Tatsikuk26 commented on hw/tatsiana_kukharskaya/test_lesson5.py
> +    for_test = "Do YoU like apple ?"  # noqa: E501
его туда по ошибке впихнула, я на работе сидела это делала, отвлекалась много)

2021-12-29 11:47 UTC, alexander-sidorov requested changes

2021-12-29 11:47 UTC, alexander-sidorov commented on hw/tatsiana_kukharskaya/test_lesson5.py
> +        == "Taaatasaiana aVasasaeasa"  # noqa: W503
```python
expected = "Taaatasaiana aVasasaeas"  # я про это
got = just_do_it4(string_for_test, char_for_test)
assert got == expected
```
вот такая проверка должна проходить

2021-12-29 12:07 UTC, alexander-sidorov requested changes

2021-12-29 12:07 UTC, alexander-sidorov commented on hw/tatsiana_kukharskaya/test_lesson5.py
> +    assert just_do_it4(string_for_test, char_for_test) == "Taaatasaiana aVasasaeasa"
Всё равно не надо символ-соединитель в конце)

2021-12-29 14:55 UTC, alexander-sidorov approved these changes

2021-12-29 15:03 UTC, maryiasa approved these changes

2021-12-29 15:05 UTC, SashaYaroshevich approved these changes

2021-12-29 15:40 UTC, alexander-sidorov approved these changes

2021-12-29 15:45 UTC, merged