Valeriya Mavritskaya - Lesson 05
alexander-sidorov/tms-qap05 pull request #115
Opened 2021-12-28 19:39 UTC by lerkin011

2021-12-28 19:54 UTC, alexander-sidorov requested changes

2021-12-28 19:54 UTC, alexander-sidorov commented on hw/valeriya_mavritskaya/test_lesson05.py
> +    assert lvl_4(some_string, symbol) == "v*a*l*"
В конце не должно быть звёздочки

2021-12-28 21:26 UTC, alexander-sidorov approved these changes

2021-12-28 21:34 UTC, vadison90125 approved these changes

2021-12-29 07:47 UTC, APOSHAml approved these changes

2021-12-29 15:06 UTC, merged