Vadim Maletski - Lesson 05 HW
alexander-sidorov/tms-qap05 pull request #116
Opened 2021-12-28 19:50 UTC by vadison90125

2021-12-28 19:57 UTC, alexander-sidorov requested changes

2021-12-28 19:57 UTC, alexander-sidorov commented on hw/vadim_maletski/func5.py
> +    p2 = tuple((p1[0], p1[-1]))  # noqa: C409
Что-то тут намудрил: flake8 прав

2021-12-28 19:57 UTC, alexander-sidorov commented on hw/vadim_maletski/func5.py
> +    index = p1.index(6)
Почему именно цифру 6 ищешь? В задании этого нет

2021-12-28 19:57 UTC, alexander-sidorov commented on hw/vadim_maletski/test_lesson5hw.py
> +        == "DO ONLY WHAT ONLY YOU CAN DO"  # noqa: W503
Не это сообщение

2021-12-28 20:08 UTC, vadison90125 commented on hw/vadim_maletski/func5.py
> +    index = p1.index(6)
т.е. создать список с одним элементом и поставить вместо 6ки? А в коллекции она должна быть, или создать этот элемент?

2021-12-28 20:10 UTC, vadison90125 commented on hw/vadim_maletski/test_lesson5hw.py
> +        == "DO ONLY WHAT ONLY YOU CAN DO"  # noqa: W503
только если сделать первый алфавит в нижнем регистре))

2021-12-28 20:41 UTC, alexander-sidorov commented on hw/vadim_maletski/func5.py
> +    index = p1.index(6)
Смысл в том, чтобы вот это работало:

```python
assert level3([a,b,c,d], c) == [a,b,c]
assert level3("xyz", "y") == "xy"
```
Независимо от a,b,c и "xyz"

2021-12-28 20:42 UTC, alexander-sidorov commented on hw/vadim_maletski/test_lesson5hw.py
> +        == "DO ONLY WHAT ONLY YOU CAN DO"  # noqa: W503
Нужно чтобы решение задачи удовлетворяло заданию, или не решать её вообще))

2021-12-28 21:25 UTC, alexander-sidorov approved these changes

2021-12-29 07:02 UTC, YaroslavBelaychuk approved these changes

2021-12-29 07:08 UTC, Zyola approved these changes

2021-12-29 07:11 UTC, merged