Andrey Yelin - Lesson 05hw
alexander-sidorov/tms-qap05 pull request #117
Opened 2021-12-28 22:45 UTC by Zyola

2021-12-29 01:52 UTC, alexander-sidorov requested changes

2021-12-29 01:52 UTC, alexander-sidorov commented on hw/andrey_yelin/Lesson_05/test_yelin_lesson05hw.py
> +    col01 = [1, 2, 3, 4, 5, 6, 7]
протестируй на 

```python
col01 = [1+1j, 1-1j, 0]
```

2021-12-29 01:52 UTC, alexander-sidorov commented on hw/andrey_yelin/Lesson_05/test_yelin_lesson05hw.py
> +    col02 = "tuda suda"
протестируй на 

```python
col02 = "aaaaaaaa                             bbbbbbbb"
```

2021-12-29 01:52 UTC, alexander-sidorov commented on hw/andrey_yelin/Lesson_05/test_yelin_lesson05hw.py
> +        == "FjOjRj jtjhjej jgjljojrjyj jojfj jtjhjej jEjmjpjejrjojr"  # noqa: W503, E501
должно быть `"j"` по условиям задачи

2021-12-29 07:13 UTC, Zyola commented on hw/andrey_yelin/Lesson_05/test_yelin_lesson05hw.py
> +        == "FjOjRj jtjhjej jgjljojrjyj jojfj jtjhjej jEjmjpjejrjojr"  # noqa: W503, E501
Перед первой "F" ?

2021-12-29 07:16 UTC, Zyola commented on hw/andrey_yelin/Lesson_05/test_yelin_lesson05hw.py
> +    col02 = "tuda suda"
Не выходит. Согласен, я по сути не функцию написал, для разных переменных, а сделал вывод определенных интервалов для строки с определенным количеством символов. Исправлю.

2021-12-29 07:30 UTC, alexander-sidorov requested changes

2021-12-29 07:30 UTC, alexander-sidorov commented on hw/andrey_yelin/Lesson_05/test_yelin_lesson05hw.py
> +        == "FjOjRj jtjhjej jgjljojrjyj jojfj jtjhjej jEjmjpjejrjojr"  # noqa: W503, E501
Нет, только буква "j" в этом случае.

2021-12-29 08:53 UTC, Zyola commented on hw/andrey_yelin/Lesson_05/test_yelin_lesson05hw.py
> +        == "FjOjRj jtjhjej jgjljojrjyj jojfj jtjhjej jEjmjpjejrjojr"  # noqa: W503, E501
Понятно. Мне следует в функции после return поменять местами string_01 и string_02

2021-12-29 19:50 UTC, alexander-sidorov requested changes

2021-12-29 19:50 UTC, alexander-sidorov commented on hw/andrey_yelin/Lesson_05/yelin_lesson05hw.py
> +    string03 = list(string02)
давай уберём лишнюю конверсию

2022-01-13 21:18 UTC, Zyola commented on hw/andrey_yelin/Lesson_05/yelin_lesson05hw.py
> +    string03 = list(string02)
Убрал лишнюю конверсию. Давай я уже вмержу ветку, чтоб не висела.

2022-01-14 06:26 UTC, vadison90125 approved these changes

2022-01-14 06:45 UTC, YaroslavBelaychuk approved these changes

2022-01-14 09:47 UTC, alexander-sidorov commented on hw/andrey_yelin/Lesson_05/yelin_lesson05hw.py
> +    return string01.join(list(string02))
Зачем тут преобразование строки в list?

2022-01-14 16:40 UTC, Zyola commented on hw/andrey_yelin/Lesson_05/yelin_lesson05hw.py
> +    return string01.join(list(string02))
Убрал обертывание в лист. Оно не нужно.

2022-01-14 19:05 UTC, alexander-sidorov approved these changes

2022-01-14 20:14 UTC, vadison90125 approved these changes

2022-01-14 20:34 UTC, APOSHAml approved these changes

2022-01-14 20:38 UTC, merged