add new file
alexander-sidorov/tms-qap05 pull request #12
Opened 2021-12-10 19:34 UTC by Tatsikuk26

2021-12-10 21:13 UTC, alexander-sidorov requested changes

2021-12-10 21:13 UTC, alexander-sidorov commented on hw/tatsiana_kukharskaya/test_hhdgf.py
> +
тесты падают из-за того, что тут две пустых строки в файле, а надо бы чтобы была ровно одна:

[Flake8 rule W391](https://www.flake8rules.com/rules/W391.html)

2021-12-10 21:15 UTC, alexander-sidorov requested changes
Прошу назвать пулл-реквест так:

<Имя> <Фамилия> - Lesson 01

имя и фамилия латиницей

скобки `<` и `>` означают обязательность

2021-12-14 15:59 UTC, MaksimPtitski submitted a review, later dismissed

2021-12-14 15:59 UTC, Tobkirill approved these changes

2021-12-14 16:23 UTC, alexander-sidorov requested changes

2021-12-14 16:23 UTC, alexander-sidorov commented on hw/tatsiana_kukharskaya/tit.txt
> +def test_example() -> None:
это должен быть `*.py` файл
это должен быть `test_`-файл

2021-12-14 16:25 UTC, alexander-sidorov requested changes
Таня, вот эти файлы:
- `hw/tatsiana_kukharskaya/.test_hhdgf.py.swp`
- `hw/tatsiana_kukharskaya/.piu.py.swp`

пожалуйста, удали из пулл реквеста.

Команда поможет:
`git rm <путь к файлу>`

2021-12-14 20:34 UTC, Tatsikuk26 commented
насчет удалить из пул реквеста файлы - я вообще не понимаю как они тут оказались, их у меня нет нигде и поэтому нет пути, пишет гит а-ля нет такого path :(

2021-12-14 20:36 UTC, Tatsikuk26 commented on hw/tatsiana_kukharskaya/tit.txt
> +def test_example() -> None:
это нужно как-то через vim исправлять? я просто намудрила сегодня совсем чувствую)

2021-12-14 20:38 UTC, alexander-sidorov requested changes

2021-12-14 20:38 UTC, alexander-sidorov commented on hw/tatsiana_kukharskaya/tit.txt
> +def test_example() -> None:
сработает вот эта команда, в корне репозитория:

`git mv hw/tatsiana_kukharskaya/tit.txt hw/tatsiana_kukharskaya/test_example.py`

2021-12-14 21:23 UTC, alexander-sidorov approved these changes

2021-12-15 11:27 UTC, maryiasa approved these changes

2021-12-15 12:33 UTC, Yancharski approved these changes

2021-12-15 12:37 UTC, merged