Andrey Yelin - Lesson 06 HW
alexander-sidorov/tms-qap05 pull request #125
Opened 2022-01-04 23:48 UTC by Zyola

2022-01-05 13:08 UTC, alexander-sidorov requested changes

2022-01-05 13:08 UTC, alexander-sidorov commented on hw/andrey_yelin/lesson06/test_lesson06hw.py
> +assert isPalindrome("") == {"data": True}
а когда это мы начали писать такие ассерты вне тест-функций? )

2022-01-05 21:30 UTC, Zyola commented on hw/andrey_yelin/lesson06/test_lesson06hw.py
> +assert isPalindrome("") == {"data": True}
Внес ассерты в функции. Почему у меня тесты не проходят в файле с функциями? В чем проблема?

2022-01-06 00:57 UTC, alexander-sidorov commented on hw/andrey_yelin/lesson06/test_lesson06hw.py
> +assert isPalindrome("") == {"data": True}
Написано, что из-за покрытия:

```
----------- coverage: platform linux, python 3.9.9-final-0 -----------
Name                                                      Stmts   Miss Branch BrPart  Cover
-------------------------------------------------------------------------------------------
hw/andrey_yelin/lesson06/functions_lesson06hw.py             37     10     16      5    72%
hw/_qa/alexander_sidorov/siarhei_apanel_test.py               5      1      0      0    80%
-------------------------------------------------------------------------------------------
TOTAL                                                      1003     11     58      5    98%

26 empty files skipped.

FAIL Required test coverage of 99.0% not reached. Total coverage: 98.49%
```

хорошо, мой файл-то, я за него отвечаю. А твой чего только на 72% тестами покрыт?

2022-01-06 15:20 UTC, alexander-sidorov requested changes

2022-01-06 15:20 UTC, alexander-sidorov commented on hw/andrey_yelin/lesson06/test_lesson06hw.py
> +    assert isPalindrome("") == {"data": True}
подсказка )

а где у тебя такая проверка?
```python
assert isPalindrome(None) == {"errors": ["none argument"]}
```
вот добавь эту проверку, и 1) найдёшь ошибку у себя в коде, и 2) покрытие тестами кода увеличится

2022-01-07 14:10 UTC, alexander-sidorov requested changes

2022-01-07 14:10 UTC, alexander-sidorov commented on hw/andrey_yelin/lesson06/functions_lesson06hw.py
> +c = [(), "", "", 1, 1]
Кажется, что это оказалось тут случайно

2022-01-08 15:42 UTC, Zyola commented on hw/andrey_yelin/lesson06/functions_lesson06hw.py
> +c = [(), "", "", 1, 1]
Это да. От проверок работы функций. Там еще принт завалялся какой-то. Все убрал.

2022-01-08 17:10 UTC, alexander-sidorov requested changes

2022-01-08 17:10 UTC, alexander-sidorov commented on hw/andrey_yelin/lesson06/functions_lesson06hw.py
> +def isPalindrome(s: Any = None) -> dict:  # noqa: N802, VNE001
тоже считаю, что flake8 тут прав и отключать эти предупреждения не надо

2022-01-08 17:10 UTC, alexander-sidorov commented on hw/andrey_yelin/lesson06/functions_lesson06hw.py
> +        result["data"] = True  # type: ignore
какая тут проблема с типизацией?

2022-01-08 17:10 UTC, alexander-sidorov commented on hw/andrey_yelin/lesson06/functions_lesson06hw.py
> +        result["data"] = False  # type: ignore
какая тут проблема с типизацией?

2022-01-08 17:10 UTC, alexander-sidorov commented on hw/andrey_yelin/lesson06/functions_lesson06hw.py
> +def multiplyArgs(*m: Any) -> dict:  # noqa: N802
считаю, что flake8 тут прав и отключать это предупреждение не нужно

2022-01-08 17:10 UTC, alexander-sidorov commented on hw/andrey_yelin/lesson06/functions_lesson06hw.py
> +def ageResult(born: Any) -> dict:  # noqa: N802
считаю, что flake8 тут прав и отключать это предупреждение не нужно

2022-01-08 17:10 UTC, alexander-sidorov commented on hw/andrey_yelin/lesson06/functions_lesson06hw.py
> +    result["data"] = {  # type: ignore
какая тут проблема с типизацией?

2022-01-08 17:10 UTC, alexander-sidorov commented on hw/andrey_yelin/lesson06/functions_lesson06hw.py
> +        t = date.today()  # noqa: VNE001
считаю, что тут flake8 прав тоже

2022-01-08 17:10 UTC, alexander-sidorov commented on hw/andrey_yelin/lesson06/functions_lesson06hw.py
> +def older(oldDate: Any) -> dict:  # noqa: N803
считаю, что тут flake8 прав тоже

2022-01-08 17:10 UTC, alexander-sidorov commented on hw/andrey_yelin/lesson06/functions_lesson06hw.py
> +    maxDate = 0  # noqa: N806
считаю, что тут flake8 прав тоже

2022-01-08 17:10 UTC, alexander-sidorov commented on hw/andrey_yelin/lesson06/functions_lesson06hw.py
> +            maxDate = int(dd.split()[0])  # noqa: N806
считаю, что тут flake8 прав тоже

2022-01-08 17:10 UTC, alexander-sidorov commented on hw/andrey_yelin/lesson06/functions_lesson06hw.py
> +def repeatingElements(elementsList: Any) -> dict:  # noqa: N802, N803
считаю, что тут flake8 прав тоже

2022-01-08 17:10 UTC, alexander-sidorov commented on hw/andrey_yelin/lesson06/functions_lesson06hw.py
> +    zy = {}  # type: ignore
какая тут проблема с типизацией?

2022-01-08 17:10 UTC, alexander-sidorov commented on hw/andrey_yelin/lesson06/functions_lesson06hw.py
> +        result["data"] = repeat  # type: ignore
какая тут проблема с типизацией?

2022-01-08 17:10 UTC, alexander-sidorov commented on hw/andrey_yelin/lesson06/test_lesson06hw.py
> +def test_isPalindrome() -> None:  # noqa: N802
тут я согласен с flake8

2022-01-08 17:10 UTC, alexander-sidorov commented on hw/andrey_yelin/lesson06/test_lesson06hw.py
> +def test_multiplyArgs() -> None:  # noqa: N802
тут я согласен с flake8

2022-01-08 17:10 UTC, alexander-sidorov commented on hw/andrey_yelin/lesson06/test_lesson06hw.py
> +def test_ageResult() -> None:  # noqa: N802
тут я согласен с flake8

2022-01-08 17:10 UTC, alexander-sidorov commented on hw/andrey_yelin/lesson06/test_lesson06hw.py
> +    d = date(year=1987, month=8, day=2)  # noqa: VNE001
тут я согласен с flake8

2022-01-08 17:10 UTC, alexander-sidorov commented on hw/andrey_yelin/lesson06/test_lesson06hw.py
> +    b = {  # noqa: VNE001
тут я согласен с flake8

2022-01-08 17:10 UTC, alexander-sidorov commented on hw/andrey_yelin/lesson06/test_lesson06hw.py
> +def test_repeatingElements() -> None:  # noqa: N802
тут я согласен с flake8

2022-01-08 17:10 UTC, alexander-sidorov commented on hw/andrey_yelin/lesson06/test_lesson06hw.py
> +    c = [(), "", "", 1]  # noqa: VNE001
тут я согласен с flake8

2022-01-10 18:08 UTC, Zyola commented on hw/andrey_yelin/lesson06/functions_lesson06hw.py
> +def isPalindrome(s: Any = None) -> dict:  # noqa: N802, VNE001
Убрал затычку

2022-01-10 18:18 UTC, Zyola commented on hw/andrey_yelin/lesson06/functions_lesson06hw.py
> +        result["data"] = True  # type: ignore
Incompatible types in assignment (expression has type "bool", target has type "str"). Объявлять значения только Any я не собираюсь, тк не будет выполняться моя проверка на None. И если не подставлять никаких значений для функии, она не отправит "none argument"  for "errors". А так все работает и даже если не вводить данные.

2022-01-10 18:19 UTC, Zyola commented on hw/andrey_yelin/lesson06/functions_lesson06hw.py
> +        result["data"] = False  # type: ignore
Таже самая история: Incompatible types in assignment (expression has type "bool", target has type "str"). Объявлять значения только Any я не собираюсь, тк не будет выполняться моя проверка на None. И если не подставлять никаких значений для функии, она не отправит "none argument" for "errors". А так все работает и даже если не вводить данные.

2022-01-10 18:53 UTC, Zyola commented on hw/andrey_yelin/lesson06/functions_lesson06hw.py
> +def ageResult(born: Any) -> dict:  # noqa: N802
Убрал, переименовал.

2022-01-10 18:53 UTC, Zyola commented on hw/andrey_yelin/lesson06/test_lesson06hw.py
> +def test_ageResult() -> None:  # noqa: N802
Убрал, переименовал.

2022-01-10 18:53 UTC, Zyola commented on hw/andrey_yelin/lesson06/test_lesson06hw.py
> +    d = date(year=1987, month=8, day=2)  # noqa: VNE001
Убрал, переименовал.

2022-01-10 18:54 UTC, Zyola commented on hw/andrey_yelin/lesson06/test_lesson06hw.py
> +def test_repeatingElements() -> None:  # noqa: N802
Убрал, переименовал.

2022-01-10 18:54 UTC, Zyola commented on hw/andrey_yelin/lesson06/test_lesson06hw.py
> +    c = [(), "", "", 1]  # noqa: VNE001
Убрал, переименовал.

2022-01-10 20:45 UTC, alexander-sidorov requested changes

2022-01-10 20:45 UTC, alexander-sidorov commented on hw/andrey_yelin/lesson06/functions_lesson06hw.py
> +def isPalindrome(s: Any = None) -> dict:  # noqa: N802, VNE001
в смысле? вот же — 

```python
# noqa: N802, VNE001
```

2022-01-10 20:45 UTC, alexander-sidorov commented on hw/andrey_yelin/lesson06/functions_lesson06hw.py
> +        result["data"] = True  # type: ignore
добавь аннотацию в строку 7, и если напомнишь, расскажу на уроке

2022-01-10 20:45 UTC, alexander-sidorov commented on hw/andrey_yelin/lesson06/functions_lesson06hw.py
> +    result = {}
```python
result: Dict[str, Any] = {}
```

тут это будет уместно

2022-01-10 20:45 UTC, alexander-sidorov commented on hw/andrey_yelin/lesson06/functions_lesson06hw.py
> +        result["data"] = True  # type: ignore
а после аннтотирования строки  7 можешь убрать этот 

```python
# type: ignore
```

2022-01-10 20:45 UTC, alexander-sidorov commented on hw/andrey_yelin/lesson06/functions_lesson06hw.py
> +        result["data"] = False  # type: ignore
аннотация `result` решит проблему

2022-01-10 20:45 UTC, alexander-sidorov commented on hw/andrey_yelin/lesson06/functions_lesson06hw.py
> +def multiplyArgs(*m: Any) -> dict:  # noqa: N802
не убрал:
```python
# noqa: N802
```

2022-01-10 20:45 UTC, alexander-sidorov commented on hw/andrey_yelin/lesson06/functions_lesson06hw.py
> +def ageResult(born: Any) -> dict:  # noqa: N802
не убрал:
```python
# noqa: N802
```

2022-01-10 20:45 UTC, alexander-sidorov commented on hw/andrey_yelin/lesson06/functions_lesson06hw.py
> +    result["data"] = {  # type: ignore
скорее всего надо сделать ту же самую аннотацию для `result`

2022-01-10 20:45 UTC, alexander-sidorov commented on hw/andrey_yelin/lesson06/functions_lesson06hw.py
> +def older(oldDate: Any) -> dict:  # noqa: N803
```python
# noqa: N802
```

2022-01-10 20:45 UTC, alexander-sidorov commented on hw/andrey_yelin/lesson06/functions_lesson06hw.py
> +    maxDate = 0  # noqa: N806
```python
# noqa: N806
```

2022-01-10 20:45 UTC, alexander-sidorov commented on hw/andrey_yelin/lesson06/functions_lesson06hw.py
> +        t = date.today()  # noqa: VNE001
```python
# noqa: VNE001
```

2022-01-10 20:45 UTC, alexander-sidorov commented on hw/andrey_yelin/lesson06/functions_lesson06hw.py
> +            maxDate = int(dd.split()[0])  # noqa: N806
```python
# noqa: N806
```

2022-01-10 20:45 UTC, alexander-sidorov commented on hw/andrey_yelin/lesson06/functions_lesson06hw.py
> +def repeatingElements(elementsList: Any) -> dict:  # noqa: N802, N803
все noqa тут надо убрать

2022-01-10 20:45 UTC, alexander-sidorov commented on hw/andrey_yelin/lesson06/test_lesson06hw.py
> +def test_ageResult() -> None:  # noqa: N802
не убрал, ещё есть:
```python
# noqa: N802
```

2022-01-10 20:45 UTC, alexander-sidorov commented on hw/andrey_yelin/lesson06/test_lesson06hw.py
> +    b = {  # noqa: VNE001
не убрал, ещё есть:
```python
# noqa: VNE001
```

2022-01-11 00:59 UTC, alexander-sidorov requested changes

2022-01-11 00:59 UTC, alexander-sidorov commented on hw/andrey_yelin/lesson06/functions_lesson06hw.py
> +def decode_7(string: Any = None) -> dict:  # noqa: CCR001
CCR001 значит, что твой код слишком сложный для понимания. Нужно это предупреждение оставить, не отключать, а вот свой код переработать

2022-01-18 20:07 UTC, alexander-sidorov requested changes
обновись плз с main, я добавлю еще тестов

если что-то надо будет починить — надо будет починить, но на дедлайн и оценку это не повлияет

2022-01-26 14:09 UTC, alexander-sidorov requested changes
активировал общие для всех тесты для твоего кода, поправь там его немного

2022-01-31 20:06 UTC, alexander-sidorov requested changes
Необходимо
1. код отремонтировать
2. типизацию расставить
3. предупреждения линтеров учесть
4. покрыть свой код тестами на 100%

2022-02-02 18:42 UTC, closed without merging