Vadim Maletski - Lesson 06 HW
alexander-sidorov/tms-qap05 pull request #128
Opened 2022-01-06 09:34 UTC by vadison90125

2022-01-06 17:07 UTC, alexander-sidorov requested changes

2022-01-06 17:07 UTC, alexander-sidorov commented on hw/vadim_maletski/test_lesson6hw.py
> +    assert level_05([]) == {"errors": ["argument must not be empty"]}
почему нет? пустая коллекция — значит 0 повторяющихся элементов, значит 

```python
{"data": {}}
```

2022-01-06 17:07 UTC, alexander-sidorov commented on hw/vadim_maletski/test_lesson6hw.py
> +        "errors": ["argument must not be empty", "argument must not be empty"]
с дабл ошибкой ты прикалываешься походу))

а ещё из двух пустых коллекций спокойно генерируется пустой словарь (ноль ключей, ноль значений)

2022-01-10 13:27 UTC, alexander-sidorov requested changes

2022-01-10 13:27 UTC, alexander-sidorov commented on hw/vadim_maletski/test_lesson6hw.py
> +    assert (level_02((1, 2))) == {"data": (1, 2)}
Добавь плз вот такие проверки, они должны проходить:
```python
assert "errors" in level_02(2, [2], 2, [2])
```

2022-01-10 13:27 UTC, alexander-sidorov commented on hw/vadim_maletski/test_lesson6hw.py
> +    ) == {"data": "A"}
добавь плз такие проверки:
```python
assert({
    1: date(1990,1,1),
    2: date(1990,1,2),
    3: date(1950,1,1),
}) == {"data": 3}
```

2022-01-10 13:27 UTC, alexander-sidorov commented on hw/vadim_maletski/func6.py
> +            res = {}  # type: ignore
какая тут проблема с типизацией возникла?

2022-01-10 13:27 UTC, alexander-sidorov commented on hw/vadim_maletski/test_lesson6hw.py
> +    assert (level_05(False)) == {"errors": ["argument must not be bool"]}
добавь плз проверки:
```python
assert "errors" in level_05(...)
assert "errors" in level_05(None)
assert "errors" in level_05(1)
assert "errors" in level_05(1.0)
assert "errors" in level_05(1j)
assert "errors" in level_05(object())
assert "errors" in level_05(object)
assert "errors" in level_05(type("_", (), {}))
assert "errors" in level_05(type)
assert "errors" in level_05(level_05)
assert "errors" in level_05(date(1999,1,1))
assert "errors" in level_05([[],[]])
```

2022-01-10 13:27 UTC, alexander-sidorov commented on hw/vadim_maletski/test_lesson6hw.py
> +    ) == {"data": "A"}
добавь плз проверки:
```python
assert "errors" in level_04(...)
assert "errors" in level_04(None)
assert "errors" in level_04(1)
assert "errors" in level_04(1.0)
assert "errors" in level_04(1j)
assert "errors" in level_04(object())
assert "errors" in level_04(object)
assert "errors" in level_04(type("_", (), {}))
assert "errors" in level_04(type)
assert "errors" in level_04(level_05)
assert "errors" in level_04(date(1999,1,1))
assert "errors" in level_04([[],[]])
```

2022-01-10 13:27 UTC, alexander-sidorov commented on hw/vadim_maletski/test_lesson6hw.py
> +    }
добавь плз проверки:
```python
assert "errors" in level_03(...)
assert "errors" in level_03(None)
assert "errors" in level_03(1)
assert "errors" in level_03(1.0)
assert "errors" in level_03(1j)
assert "errors" in level_03(object())
assert "errors" in level_03(object)
assert "errors" in level_03(type("_", (), {}))
assert "errors" in level_03(type)
assert "errors" in level_03(level_03)
assert "errors" in level_03([[],[]])
```

2022-01-10 13:27 UTC, alexander-sidorov commented on hw/vadim_maletski/test_lesson6hw.py
> +    assert (level_06(9)) == {"errors": ["argument (query=9) must be string"]}
добавь плз проверки:
```python
assert "errors" in level_06(...)
assert "errors" in level_06(None)
assert "errors" in level_06(1.0)
assert "errors" in level_06(1j)
assert "errors" in level_06(object())
assert "errors" in level_06(object)
assert "errors" in level_06(type("_", (), {}))
assert "errors" in level_06(type)
assert "errors" in level_06(level_05)
assert "errors" in level_06(date(1999,1,1))
assert "errors" in level_06([[],[]])
```

2022-01-10 13:27 UTC, alexander-sidorov commented on hw/vadim_maletski/func6.py
> +        s2 = (f"{key}{value}" for (key, value) in s2.items())  # type: ignore
какая проблема с типизацией тут возникла?

2022-01-10 13:27 UTC, alexander-sidorov commented on hw/vadim_maletski/func6.py
> +            el += 1  # noqa: SIM113
вот тут  flake8 прав

2022-01-10 13:27 UTC, alexander-sidorov commented on hw/vadim_maletski/test_lesson6hw.py
> +    assert (level_09(None)) == {"errors": ["argument must not be empty"]}
добавь плз проверки:
```python
assert "errors" in level_09(...)
assert "errors" in level_09(1)
assert "errors" in level_09(1.0)
assert "errors" in level_09(1j)
assert "errors" in level_09(object())
assert "errors" in level_09(object)
assert "errors" in level_09(type("_", (), {}))
assert "errors" in level_09(type)
assert "errors" in level_09(level_05)
assert "errors" in level_09(date(1999,1,1))
assert "errors" in level_09([[],[]])
```

2022-01-10 13:27 UTC, alexander-sidorov commented on hw/vadim_maletski/test_lesson6hw.py
> +    assert (level_10(None, None, None, None)) == {
Добавь плз проверки:

```python
assert level_10("ab", "cd") == {"data": {"a": "c", "b": "d"}}
assert level_10("", "") == {"data": {}}
```

`+ добавь проверки из самого задания

2022-01-10 13:27 UTC, alexander-sidorov commented on hw/vadim_maletski/test_lesson6hw.py
> +    assert (level_11("{}", "{}")) == {
добавь плз проверки:
```python
assert "errors" in level_11(..., ...)
assert "errors" in level_11(None, ...)
assert "errors" in level_11(1.0, None)
assert "errors" in level_11(1j, object)
assert "errors" in level_11(object(), object())
assert "errors" in level_11(object, 1j)
assert "errors" in level_11(type("_", (), {}), "a")
assert "errors" in level_11(type, [])
assert "errors" in level_11(level_05, {})
assert "errors" in level_11(date(1999,1,1), {})
assert "errors" in level_11([[],[]], frozenset())
assert level_11(frozenset(), frozenset()) == {
    "data": {
           "a&b": {},
            "a|b": {},
            "a-b": {},
            "b-a": {},
            "|a-b|": {},
            "a in b": True,
            "b in a": True,
    }
}
```

2022-01-10 13:27 UTC, alexander-sidorov commented on hw/vadim_maletski/test_lesson6hw.py
> +    assert (level_12((1, 2))) == {"data": {1: 2}}
добавь плз проверки:

```python
assert level_12(1,2,3,"a",5,{},6,object) == {
    1: 2,
    3: "a",
    5: {},
    6: object,
}
```

2022-01-11 00:55 UTC, alexander-sidorov requested changes
вместо тысячи комментов добавил тесты

2022-01-17 18:33 UTC, alexander-sidorov requested changes
добавил тесты

2022-01-18 20:06 UTC, alexander-sidorov requested changes
обновись плз с main, я добавлю еще тестов

если что-то надо будет починить — надо будет починить, но на дедлайн и оценку это не повлияет

2022-01-18 20:26 UTC, vadison90125 commented
> обновись плз с main, я добавлю еще тестов
> 
> если что-то надо будет починить — надо будет починить, но на дедлайн и оценку это не повлияет

ok, сейчас обновлюсь. Вчерашние тесты фиксю. Всё зелёное кроме этого:
"v-17": (azaza("3", bs=[tuple]), "a", {3: "a"}),

эти проходят:
"v-15": (azaza("1", bs=[list]), "a", {"1": "a"}),
"v-16": (azaza("2", bs=[str]), "a", {"2": "a"}),

"1"  --  "1"
"2"  --  "2"
"3"  --   3 ???    Пока недопонимаю как работает bs=[tuple])

2022-01-26 14:00 UTC, alexander-sidorov requested changes
активировал общие для всех тесты на твоём коде: один тестик упал, фиксится одной строкой.

так всё ок

2022-01-27 18:29 UTC, alexander-sidorov requested changes
пожалуйста, протестируй свой код, который не покрыт тестами - или удали его за ненадобностью  - и будем мержить ПР

2022-01-28 09:08 UTC, alexander-sidorov approved these changes

2022-01-28 09:08 UTC, alexander-sidorov commented on hw/vadim_maletski/func6.py
> +            el += 1
Здесь ты очевидно перебираешь все элементы коллекции по порядку, без задержек и переходов на предыдущие перебранные. Не надо вручную увеличивать индекс на +1, надо перебрать коллекцию инструкцией for:

```python
for elm in col_letter:
    rr = len(elm)
    num.append(str(rr))
```

А еще лучше использовать list comprehension:

```python
num = [str(len(elm)) for elm in col_letter]
```

2022-01-31 18:51 UTC, Zyola approved these changes

2022-01-31 18:52 UTC, YaroslavBelaychuk approved these changes

2022-01-31 18:55 UTC, alexander-sidorov approved these changes

2022-01-31 18:59 UTC, merged