test_yelin_first_lesson_01.py
alexander-sidorov/tms-qap05 pull request #13
Opened 2021-12-10 19:48 UTC by Zyola

2021-12-10 21:10 UTC, alexander-sidorov requested changes

2021-12-10 21:10 UTC, alexander-sidorov commented on hw/andrey_yelin/test_yelin.py
> +
тесты падают из-за того, что тут лишняя пустая строка: два раза Энтер нажат
а надо один

2021-12-10 22:12 UTC, alexander-sidorov requested changes
Прошу назвать пулл-реквест так:

<Имя> <Фамилия> - Lesson 01

имя и фамилия латиницей

скобки `<` и `>` означают обязательность

2021-12-14 19:58 UTC, Zyola reviewed
Done

2021-12-14 20:17 UTC, alexander-sidorov approved these changes

2021-12-14 20:29 UTC, YaroslavBelaychuk approved these changes

2021-12-14 20:29 UTC, denisasipenko approved these changes

2021-12-14 20:33 UTC, MaksimPtitski approved these changes

2021-12-14 20:56 UTC, merged