Siarhei Apanel - Lesson 06 HW
alexander-sidorov/tms-qap05 pull request #130
Opened 2022-01-06 10:23 UTC by APOSHAml

2022-01-06 15:47 UTC, alexander-sidorov requested changes

2022-01-06 15:47 UTC, alexander-sidorov commented on hw/siarhei_apanel/test_hw.py
> +    assert new_set({1}, {1, 2})["data"]["a in b"] == True  # noqa: E712
```python
# noqa: E712
```
такую ошибку нельзя игнорить в этом случае )

2022-01-06 15:47 UTC, alexander-sidorov commented on hw/siarhei_apanel/test_hw.py
> +    assert new_set({1}, {1, 2})["data"]["b in a"] == False  # noqa: E712
и в этом)

2022-01-06 18:00 UTC, alexander-sidorov requested changes

2022-01-06 18:00 UTC, alexander-sidorov commented on hw/siarhei_apanel/test_hw.py
> +    # assert proizvedenie("1", "3") == {"errors": ["TypeError"]} # noqa: E800, E501
давай все эти проверки раскомментим, или удалим.

2022-01-07 12:15 UTC, alexander-sidorov submitted a review, later dismissed

2022-01-08 17:12 UTC, alexander-sidorov submitted a review, later dismissed

2022-01-09 18:21 UTC, YaroslavBelaychuk approved these changes

2022-01-10 12:41 UTC, alexander-sidorov requested changes
@maryiasa +2 qa

2022-01-10 12:41 UTC, alexander-sidorov commented on hw/_qa/maria_saganovich/test_siarhei_func10_new_dict_hw6.py
> +    assert new_dict("", []) == {"errors": ["args are empty"]}
@maryiasa Маша, не обязательно :)

из пустых коллекций (0 ключей, 0 значений) спокойно собирается пустой словарь (0 ключей, 0 значений)

2022-01-10 12:41 UTC, alexander-sidorov commented on hw/_qa/maria_saganovich/test_siarhei_func11_new_set_hw6.py
> +    assert new_set({""}, []) == {  # noqa: JS101
@maryiasa не обязательно требовать конкретные ошибки (автор может их называть по-своему). Наша задача убедиться, что функция в принципе сигнализирует правильно об ошибках, и они в заданном формате.

здесь (и далее) можно делать проверки:
```python
result = new_set({""}, [])
errors = result.get("errors")
assert errors
assert errors == sorted(errors)
```

2022-01-10 12:41 UTC, alexander-sidorov commented on hw/_qa/maria_saganovich/test_siarhei_func12_diction_hw6.py
> +        "data": {1: 2, 3: 4, 5: 6, 7: None, 9: None}
@maryiasa 
ну неправда! чётные/нечётные в смысле их местоположения!

```python
assert diction("a", {}, "c", []) == {"a": {}, "b": []}
```

2022-01-10 12:41 UTC, alexander-sidorov commented on hw/_qa/maria_saganovich/test_siarhei_func12_diction_hw6.py
> +        "data": {1: 2, 3: 4, 5: 6, ...: [8, 10]}
@maryiasa это ты с 10 задачей перепутала?)

2022-01-10 12:41 UTC, alexander-sidorov commented on hw/_qa/maria_saganovich/test_siarhei_html_str_hw6.py
> +    assert html_str("") == {"errors": ["query is empty"]}
@maryiasa  неправда) здесь можно и без ошибки

2022-01-10 12:41 UTC, alexander-sidorov commented on hw/_qa/maria_saganovich/test_siarhei_html_str_hw6.py
> +    assert html_str([]) == {"errors": ["arg should be str"]}
@maryiasa +1 !!
только поменяй проверку плз, на наличие ошибок, а не на проверку на конкретный текст (это право автора)

2022-01-10 12:41 UTC, alexander-sidorov commented on hw/_qa/maria_saganovich/test_siarhei_palindrome_hw6.py
> +    assert palindrom(args) == {"data": True}
@maryiasa формально это не будет палиндромом, т.к. символы отличаются

2022-01-10 12:41 UTC, alexander-sidorov commented on hw/_qa/maria_saganovich/test_siarhei_repeat_hw6.py
> +        "errors": ["arg shouldn't be empty"]
@maryiasa автор другой текст пишет, так что просто проверь наличие ошибок

а так +1

2022-01-10 12:41 UTC, alexander-sidorov commented on hw/_qa/maria_saganovich/test_siarhei_repeat_hw6.py
> +    assert repeat(c2) == {"data": ["no duplicates"]}
@maryiasa ничего подобного) тут по-хорошему должна быть `{"data": {}}`

но т.к. у автора есть упоминания в коде на "нет повторений", то тогда уж стоит проверять на наличие ошибок только лишь

2022-01-10 12:53 UTC, maryiasa commented on hw/_qa/maria_saganovich/test_siarhei_palindrome_hw6.py
> +    assert palindrom(args) == {"data": True}
палиндромом же считается то, что одинаково читается с двух сторон, а то как оно записано, на чтение никак ведь не влияет

2022-01-10 13:31 UTC, maryiasa commented on hw/_qa/maria_saganovich/test_siarhei_func12_diction_hw6.py
> +        "data": {1: 2, 3: 4, 5: 6, ...: [8, 10]}
@alexander-sidorov не, просто решила применить знания, полученные в 10 задаче, при выполнении 12)

2022-01-10 20:16 UTC, maryiasa commented on hw/_qa/maria_saganovich/test_siarhei_func10_new_dict_hw6.py
> +    assert new_dict("", []) == {"errors": ["args are empty"]}
removed

2022-01-10 20:16 UTC, maryiasa commented on hw/_qa/maria_saganovich/test_siarhei_func11_new_set_hw6.py
> +    assert new_set({""}, []) == {  # noqa: JS101
fixed

2022-01-10 20:19 UTC, maryiasa commented on hw/_qa/maria_saganovich/test_siarhei_func12_diction_hw6.py
> +        "data": {1: 2, 3: 4, 5: 6, 7: None, 9: None}
check was removed

2022-01-10 20:19 UTC, maryiasa commented on hw/_qa/maria_saganovich/test_siarhei_html_str_hw6.py
> +    assert html_str("") == {"errors": ["query is empty"]}
check was removed

2022-01-10 20:19 UTC, maryiasa commented on hw/_qa/maria_saganovich/test_siarhei_html_str_hw6.py
> +    assert html_str([]) == {"errors": ["arg should be str"]}
fixed

2022-01-10 20:20 UTC, maryiasa commented on hw/_qa/maria_saganovich/test_siarhei_repeat_hw6.py
> +        "errors": ["arg shouldn't be empty"]
fixed

2022-01-10 20:20 UTC, maryiasa commented on hw/_qa/maria_saganovich/test_siarhei_repeat_hw6.py
> +    assert repeat(c2) == {"data": ["no duplicates"]}
check was removed

2022-01-10 20:34 UTC, alexander-sidorov commented on hw/_qa/maria_saganovich/test_siarhei_palindrome_hw6.py
> +    assert palindrom(args) == {"data": True}
добавлю уточнение в задание, что "текст, который читается", надо воспринимать в контексте текста в Python и "чтения текста" в Python :)

2022-01-10 20:37 UTC, alexander-sidorov requested changes
@maryiasa поправь плз свои тесты)

2022-01-10 20:37 UTC, alexander-sidorov commented on hw/_qa/maria_saganovich/test_siarhei_func11_new_set_hw6.py
> +    assert errors == sorted(errors)
ой класс, а проверь плз до этого, что `errors` это `list`

2022-01-10 20:37 UTC, alexander-sidorov commented on hw/_qa/maria_saganovich/test_siarhei_repeat_hw6.py
> +def test_func5_repeat():
типизация где?? ))

2022-01-10 20:49 UTC, maryiasa commented on hw/_qa/maria_saganovich/test_siarhei_repeat_hw6.py
> +def test_func5_repeat():
fixed

2022-01-10 20:49 UTC, maryiasa commented on hw/_qa/maria_saganovich/test_siarhei_func11_new_set_hw6.py
> +    assert errors == sorted(errors)
check is added

2022-01-10 21:29 UTC, alexander-sidorov approved these changes

2022-01-11 17:33 UTC, maryiasa approved these changes

2022-01-12 16:08 UTC, YaroslavBelaychuk approved these changes

2022-01-12 16:09 UTC, merged