Kirill Tobolich - Lesson 06 HW
alexander-sidorov/tms-qap05 pull request #132
Opened 2022-01-09 15:11 UTC by Tobkirill

2022-01-10 10:47 UTC, alexander-sidorov requested changes

2022-01-10 10:47 UTC, alexander-sidorov commented on hw/kirill_tobolich/lesson6_hw.py
> +def zip_collections_to_dict(  # noqa: CCR001
здесь flake8 совершенно прав. Функция огромная и сложная для понимания, поэтому стоит подумать, как её упростить

2022-01-10 10:47 UTC, alexander-sidorov commented on hw/kirill_tobolich/test_lesson6_hw.py
> +
добавь плз вот такие проверки, они должны проходить:
```python
assert multiply("a", 2) == "a"
assert multiply(2, [1], 2) = [1,1,1,1]
assert multiply("a") == "a"
```

2022-01-10 10:47 UTC, alexander-sidorov commented on hw/kirill_tobolich/test_lesson6_hw.py
> +        "errors": "given argument with keys is not a list, str or tuple"
число - понятно
но что не так с другими коллекциями? )
для них можно было бы тоже возвращать результат

```python
{"data": {}}
```

как думаешь?

2022-01-10 10:47 UTC, alexander-sidorov commented on hw/kirill_tobolich/test_lesson6_hw.py
> +
добавь ещё плз эту проверку, она должна проходить
```python
assert http_query_parser("xxx=&yyy=") == {"xxx": [""], "yyy": [""]}
```

2022-01-10 10:47 UTC, alexander-sidorov commented on hw/kirill_tobolich/test_lesson6_hw.py
> +
добавь ещё плз такую проверку, она должна проходить:
```python
assert repeat_chars("a11") == "aaaaaaaaaaa"
```

2022-01-10 10:47 UTC, alexander-sidorov commented on hw/kirill_tobolich/test_lesson6_hw.py
> +
добавь плз вот эту проверку ещё, она должна проходить:
```python
assert count_chars("a1b1a1") == "aba"
```

2022-01-10 16:10 UTC, Tobkirill commented on hw/kirill_tobolich/test_lesson6_hw.py
> +        "errors": "given argument with keys is not a list, str or tuple"
У меня эта функция работает для list, str or tuple и возвращает для них результат, одну из проверок я сделал в том числе и для tuple. 
Число как негативный тест было. Или я не понял вопрос?)

2022-01-10 16:15 UTC, Tobkirill commented on hw/kirill_tobolich/test_lesson6_hw.py
> +
Возможно, ты имел ввиду добавить это в тест test_repeat_chars?

2022-01-10 17:44 UTC, Tobkirill commented on hw/kirill_tobolich/lesson6_hw.py
> +def zip_collections_to_dict(  # noqa: CCR001
done

2022-01-10 17:44 UTC, Tobkirill commented on hw/kirill_tobolich/test_lesson6_hw.py
> +
done

2022-01-10 17:45 UTC, Tobkirill commented on hw/kirill_tobolich/test_lesson6_hw.py
> +
done

2022-01-10 17:45 UTC, Tobkirill commented on hw/kirill_tobolich/test_lesson6_hw.py
> +
done

2022-01-10 20:31 UTC, alexander-sidorov requested changes
и проверь плз, что в каждом случае ошибки функции возвращают `List[str]`, а не `str`

2022-01-10 20:31 UTC, alexander-sidorov commented on hw/kirill_tobolich/lesson6_hw.py
> +    types = (list, str, tuple)
вот я об этом — что если вызвать функцию:

```python
r = get_the_same_elements_in_collection({1,2,3,4,5})
```

почему она не хочет работать? ведь в этом случае можно выдать

```python
{"data": {}}
```

как считаешь?

2022-01-10 20:31 UTC, alexander-sidorov commented on hw/kirill_tobolich/lesson6_hw.py
> +    counter: Counter = Counter()
я именно эту функцию имел в виду:

```python
In [4]: count_chars("")
Out[4]: {'data': ''}

In [5]: count_chars("a")
Out[5]: {'data': 'a1'}

In [6]: count_chars("ab")
Out[6]: {'data': 'a1b1'}

In [7]: count_chars("aba")
Out[7]: {'data': 'a2b1'}  # а должно быть: "a1b1a1"
```

2022-01-11 00:03 UTC, alexander-sidorov requested changes

2022-01-11 00:03 UTC, alexander-sidorov commented on hw/kirill_tobolich/lesson6_hw.py
> +    numbers = re.findall("\d+", string)  # noqa: W605
это предупреждение не следует отключать

2022-01-11 00:03 UTC, alexander-sidorov commented on hw/kirill_tobolich/lesson6_hw.py
> +    chars = re.findall("\D", string)  # noqa: W605
это предупреждение не следует отключать

2022-01-11 00:14 UTC, alexander-sidorov requested changes
вместо тысячи комментов добавил тесты

2022-01-11 17:12 UTC, Tobkirill commented on hw/kirill_tobolich/lesson6_hw.py
> +    counter: Counter = Counter()
Переделал функцию, ща работает

2022-01-11 17:13 UTC, Tobkirill commented on hw/kirill_tobolich/lesson6_hw.py
> +    chars = re.findall("\D", string)  # noqa: W605
исправил

2022-01-11 20:38 UTC, alexander-sidorov commented on hw/kirill_tobolich/test_lesson6_hw.py
> +    assert count_chars("aaabb111!!") == {"data": "a3b213!2"}
вот этот кейс я бы трактовал как ошибочный: иначе обратное преобразование будет работать неверно:

```python
x = "aaabb111!!"
y = task_8(x)  # "a3b213!2"
x_ = task_7(y)  # "aaabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb!!"
x == x_  # False
```

2022-01-11 20:49 UTC, Tobkirill commented on hw/kirill_tobolich/test_lesson6_hw.py
> +    assert count_chars("aaabb111!!") == {"data": "a3b213!2"}
Тут скорее всего зависит от условия. В задаче 7 у нас 1 символ после которого идёт число. Изначально моё решение было как 1 символ соответствует 1 цифре, я понял условие так. Потом ты добавил тест, как бы намекнул, что после символа может быть числа больше однозначного.
В 8 задаче нужно посчитать количество раз повторений символа.
В итоге, несмотря на то, что условия задачи кажутся обратными, у них все-таки есть различие в интерпретации данных.

2022-01-11 21:20 UTC, alexander-sidorov commented on hw/kirill_tobolich/test_lesson6_hw.py
> +    assert count_chars("aaabb111!!") == {"data": "a3b213!2"}
Тогда и тест мой поправь

2022-01-11 21:21 UTC, alexander-sidorov approved these changes

2022-01-12 19:00 UTC, MaksimPtitski approved these changes

2022-01-18 16:21 UTC, APOSHAml approved these changes

2022-01-18 20:05 UTC, alexander-sidorov requested changes
обновись плз с main, я добавлю тестов

если что-то надо будет починить — надо будет починить, но на дедлайн и оценку это не повлияет

2022-01-26 13:40 UTC, alexander-sidorov requested changes
активировал общие для всех тесты для твоего кода. его нужно слегка починить

2022-01-31 19:51 UTC, alexander-sidorov requested changes
ждём отремонтированный код)

2022-02-02 18:42 UTC, closed without merging