Valeriya Mavritskaya - Lesson 06 hw
alexander-sidorov/tms-qap05 pull request #133
Opened 2022-01-09 18:55 UTC by lerkin011

2022-01-10 11:36 UTC, alexander-sidorov requested changes
очень классная работа проделана! 👍🏻👍🏻

2022-01-10 11:36 UTC, alexander-sidorov commented on hw/valeriya_mavritskaya/lesson06/test_homework06.py
> +
добавь плз проверки, они должны проходить:
```python
assert if_palindrome_1("a   a a") is False
assert "errors" in if_palindrome_1(...)

```

2022-01-10 11:36 UTC, alexander-sidorov commented on hw/valeriya_mavritskaya/lesson06/test_homework06.py
> +
добавь плз проверки:
```python
assert multiplication_2(2, 1j) == 2j
assert multiplication_2(0.25, 4) == 1.0
assert multiplication_2("a", 2) == "aa"
assert multiplication_2(2, "a") == "aa"
assert multiplication_2(2, "a", 2) == "aaaa"
assert multiplication_2(2, [2], 2) == [2,2,2,2]
assert "errors" in multiplication_2(...)
```

2022-01-10 11:36 UTC, alexander-sidorov commented on hw/valeriya_mavritskaya/lesson06/test_homework06.py
> +
добавь плз:
```python
assert "errors" in birthday_3(...)
```

2022-01-10 11:36 UTC, alexander-sidorov commented on hw/valeriya_mavritskaya/lesson06/test_homework06.py
> +
добавь плз:
```python
assert oldest_4({1: date(1990, 1, 1), 2: date(2000, 1, 1)}) == 1
assert "errors" in oldest_4(...)
```

2022-01-10 11:36 UTC, alexander-sidorov commented on hw/valeriya_mavritskaya/lesson06/test_homework06.py
> +
добавь плз:
```python
assert "errors" in duplicates_5([{}, {}])
assert "errors" in duplicates_5(...)
```

2022-01-10 11:36 UTC, alexander-sidorov commented on hw/valeriya_mavritskaya/lesson06/test_homework06.py
> +
добавь плз:
```python
assert "errors" in dict_from_http_6(...)
```

2022-01-10 11:36 UTC, alexander-sidorov commented on hw/valeriya_mavritskaya/lesson06/test_homework06.py
> +
добавь плз:
```python
assert "errors" in repeated_symbols_7(...)
```

2022-01-10 11:36 UTC, alexander-sidorov commented on hw/valeriya_mavritskaya/lesson06/test_homework06.py
> +
добавь плз:
```python
assert count_amount_8("aabba") == "a2b2a1"
assert "errors" in count_amount_8(...)
```

2022-01-10 11:36 UTC, alexander-sidorov commented on hw/valeriya_mavritskaya/lesson06/test_homework06.py
> +
добавь плз:
```python
assert revert_dictionary_9({"aa": "bb"}) == {"bb": "aa"}
assert "errors" in revert_dictionary_9(...)
```

2022-01-10 11:36 UTC, alexander-sidorov commented on hw/valeriya_mavritskaya/lesson06/test_homework06.py
> +
добавь плз:
```python
assert "errors" in join_dictionary_10(..., ...)
```

2022-01-10 11:36 UTC, alexander-sidorov commented on hw/valeriya_mavritskaya/lesson06/test_homework06.py
> +
добавь плз:
```python
assert "errors" in set_operations_11({}, [])
```

2022-01-10 11:36 UTC, alexander-sidorov commented on hw/valeriya_mavritskaya/lesson06/test_homework06.py
> +    }
добавь плз:
```python
assert mk_dictionary_12(1, [], 2, {}) == {1: [], 2: {}}
assert "errors" in mk_dictionary_12(1)
```

2022-01-10 16:17 UTC, lerkin011 commented on hw/valeriya_mavritskaya/lesson06/test_homework06.py
> +
почему первые два False? по логике подходят под палиндром
![image](https://user-images.githubusercontent.com/75045511/148799799-ee94da19-c93e-47d2-a75d-d7ac1c53e0a4.png)

2022-01-10 17:45 UTC, lerkin011 commented on hw/valeriya_mavritskaya/lesson06/test_homework06.py
> +
про первый assert - такого условия не было в задаче, чтобы считать только символы подряд =) 
у меня возвращает Actual   :{'data': 'a3b2'}

2022-01-10 18:55 UTC, lerkin011 commented on hw/valeriya_mavritskaya/lesson06/homework06_functions.py
> +        result["error"] = "Date should be in the past"  # type: ignore
Нужна помощь. Я не понимаю, на что он ругается 
<img width="1440" alt="Screenshot 2022-01-10 at 21 53 16" src="https://user-images.githubusercontent.com/75045511/148822697-c4a57a73-e122-48cb-b72c-0717676a383c.png">

2022-01-10 20:00 UTC, alexander-sidorov commented on hw/valeriya_mavritskaya/lesson06/test_homework06.py
> +
понимаю) будем считать, что _"текст, читающийся одинаково в обоих направлениях"_, подчиняется правилам чтения текста в Python, где **все** символы важны

2022-01-10 20:04 UTC, alexander-sidorov commented on hw/valeriya_mavritskaya/lesson06/homework06_functions.py
> +        result["error"] = "Date should be in the past"  # type: ignore
дело в том, что `result` у тебя — это словарь, и в строках 41~49 он у тебя наполняется парами (ключ: строка, значение: число)

отсюда mypy выводит, что тип твоего словаря — `Dict[str, int]`

а потом видит, что ты в строке 51 в качестве значения присваеваешь строку! а вроде как ключи - это числа.

вот mypy и ругается.

А глобально у тебя проблема в том, что в result разрешены только ключи "errors" или "data.
А не "age"  итд.

посмотри чужие ПР, там наглядно видна правильная структура результата

2022-01-10 20:05 UTC, alexander-sidorov commented on hw/valeriya_mavritskaya/lesson06/test_homework06.py
> +
хорошо, сейчас добавлю в описание дз :)

2022-01-10 20:22 UTC, alexander-sidorov requested changes

2022-01-10 20:22 UTC, alexander-sidorov commented on hw/valeriya_mavritskaya/lesson06/test_homework06.py
> +
забыла последнюю проверку из моего списка добавить
```python
assert "errors" in multiplication_2(...)

# и ещё вот эти добавь плз
assert "errors" in multiplication_2(object())
```

2022-01-10 20:22 UTC, alexander-sidorov commented on hw/valeriya_mavritskaya/lesson06/test_homework06.py
> +
Не забудь крайнюю проверку из первого коммента добавить)

2022-01-10 20:22 UTC, alexander-sidorov commented on hw/valeriya_mavritskaya/lesson06/test_homework06.py
> +    assert if_palindrome_1("") == {"data": "This is a palindrome"}
должно быть
```python
{"data": True}
```

2022-01-10 20:22 UTC, alexander-sidorov commented on hw/valeriya_mavritskaya/lesson06/test_homework06.py
> +    assert if_palindrome_1("x") == {"data": "This is a palindrome"}
должно быть
```python
{"data": True}
```

2022-01-10 20:22 UTC, alexander-sidorov commented on hw/valeriya_mavritskaya/lesson06/test_homework06.py
> +    assert if_palindrome_1("xx") == {"data": "This is a palindrome"}
должно быть
```python
{"data": True}
```

2022-01-10 20:22 UTC, alexander-sidorov commented on hw/valeriya_mavritskaya/lesson06/test_homework06.py
> +    assert if_palindrome_1("xy") == {"data": "This is not a palindrome"}
должно быть
```python
{"data": False}
```

2022-01-10 20:22 UTC, alexander-sidorov commented on hw/valeriya_mavritskaya/lesson06/test_homework06.py
> +    assert if_palindrome_1(True) == {"error": "Input must be a string"}  # type: ignore  # noqa: E501
добавь пожалуйста
```python
assert "errors" in if_palindrome_1(True)
```

2022-01-10 20:22 UTC, alexander-sidorov commented on hw/valeriya_mavritskaya/lesson06/test_homework06.py
> +        "data": "This is a palindrome"
должно быть
```python
{"data": False}
```

2022-01-10 20:22 UTC, alexander-sidorov commented on hw/valeriya_mavritskaya/lesson06/test_homework06.py
> +    assert if_palindrome_1(...) == {"error": "Input must be a string"}  # type: ignore  # noqa: E501
добавь пожалуйста
```python
assert "errors" in if_palindrome_1(...)
```

2022-01-10 20:22 UTC, alexander-sidorov commented on hw/valeriya_mavritskaya/lesson06/test_homework06.py
> +    assert if_palindrome_1("a   a a") == {"data": "This is a palindrome"}
должно быть
```python
{"data": False}
```

2022-01-10 20:22 UTC, alexander-sidorov commented on hw/valeriya_mavritskaya/lesson06/test_homework06.py
> +    assert if_palindrome_1("Aaa") == {"data": "This is a palindrome"}
должно быть
```python
{"data": False}
```

2022-01-10 20:22 UTC, alexander-sidorov commented on hw/valeriya_mavritskaya/lesson06/test_homework06.py
> +
добавь плз)

```python
assert "errors" in birthday_3(...)
```

2022-01-10 20:22 UTC, alexander-sidorov commented on hw/valeriya_mavritskaya/lesson06/test_homework06.py
> +    assert oldest_4(...) == {"error": "Input must be a dictionary"}  # type: ignore  # noqa: E501
добавь плз)
```python
assert "errors" in oldest_4(...)
assert "errors" in oldest_4(object())
```

2022-01-10 20:22 UTC, alexander-sidorov commented on hw/valeriya_mavritskaya/lesson06/test_homework06.py
> +
всё-таки добавь мои проверки плз)

2022-01-10 20:22 UTC, alexander-sidorov commented on hw/valeriya_mavritskaya/lesson06/test_homework06.py
> +
всё-таки добавь мои проверки)

2022-01-10 20:22 UTC, alexander-sidorov commented on hw/valeriya_mavritskaya/lesson06/test_homework06.py
> +
и всё-таки добавь мои проверки)

2022-01-10 20:22 UTC, alexander-sidorov commented on hw/valeriya_mavritskaya/lesson06/test_homework06.py
> +
всё-таки добавь мои проверки)

2022-01-10 20:22 UTC, alexander-sidorov commented on hw/valeriya_mavritskaya/lesson06/test_homework06.py
> +
всё-таки добавь мои проверки)

2022-01-10 20:22 UTC, alexander-sidorov commented on hw/valeriya_mavritskaya/lesson06/test_homework06.py
> +
всё-таки добавь мои проверки)

2022-01-10 20:22 UTC, alexander-sidorov commented on hw/valeriya_mavritskaya/lesson06/test_homework06.py
> +    }
всё-таки добавь мои проверки)

2022-01-10 22:37 UTC, alexander-sidorov requested changes
вместо тысячи комментов добавил тебе тесты)

2022-01-18 20:03 UTC, alexander-sidorov requested changes
обновись плз с main, я добавлю тестов

их нужно будет учесть и пофиксить код. но на дедлайн и оценку это не повлияет

однако сейчас у тебя 10 за лямбду на уроке и 0 за домашку - нету декоратора

2022-02-02 18:42 UTC, closed without merging