Maria Saganovich - Lesson 06 Hw
alexander-sidorov/tms-qap05 pull request #135
Opened 2022-01-09 22:47 UTC by maryiasa

2022-01-10 12:11 UTC, alexander-sidorov requested changes

2022-01-10 12:11 UTC, alexander-sidorov commented on hw/maria_saganovich/lesson6_hw/lvl6_dict_http_query.py
> +            data = str(query).split("&")
зачем строку в строку преобразовывать?

2022-01-10 12:11 UTC, alexander-sidorov commented on hw/maria_saganovich/lesson6_hw/lvl7_str_duplicate_char.py
> +            res = re.findall("([a-zA-Z]+\d+)", arg)  # noqa: W605
не надо это игнорить)

2022-01-10 12:11 UTC, alexander-sidorov commented on hw/maria_saganovich/lesson6_hw/lvl7_str_duplicate_char.py
> +                res2 = re.split("(\d+)", value)  # noqa: W605
и это)

2022-01-10 12:11 UTC, alexander-sidorov commented on hw/maria_saganovich/lesson6_hw/lvl9_swap_keys_values.py
> +                if value in result_data.keys():  # noqa: SIM118
flake8 тут прав

2022-01-10 12:11 UTC, alexander-sidorov commented on hw/maria_saganovich/lesson6_hw/test_lvl10_empty_keys_values.py
> +    assert func10_empty_keys_values("sdv", {}) == {"errors": ["incorrect arg"]}
добавь плз проверки, они должны работать:
```python
assert func10_empty_keys_values([1,2], "ab") == {"data": {1:"a", 2:"b"}}
```

2022-01-10 12:11 UTC, alexander-sidorov commented on hw/maria_saganovich/lesson6_hw/test_lvl12_even_keys_odd_values.py
> +    }
добавь плз проверки, они должны работать:
```python
assert func12_even_keys_odd_values("a", [], 2, {}) == {"data": {"a": [], 2: {}}}
```

2022-01-10 12:11 UTC, alexander-sidorov commented on hw/maria_saganovich/lesson6_hw/test_lvl1_palindrome.py
> +    assert func1_palindrome("Do geese    se e God  ") == {"data": True}
добавь плз проверки, они должны работать:
```python
assert func1_palindrome("a  a a") == {"data": False}
assert func1_palindrome("Aaa") == {"data": False}
```

2022-01-10 12:11 UTC, alexander-sidorov commented on hw/maria_saganovich/lesson6_hw/test_lvl2_product.py
> +    assert func2_product((1 + 2j), (3 + 4j)) == {"data": (-5 + 10j)}
добавь плз проверки, они должны работать:
```python
assert func2_product(2, "a") == {"data": "aa"}
assert func2_product(2, [2]) == {"data": [2,2]}
assert func2_product(2, [2], 2) == {"data": [2,2,2,2]}
assert "errors" in func2_product(2, [2], 2, [2])
```

2022-01-10 12:11 UTC, alexander-sidorov commented on hw/maria_saganovich/lesson6_hw/test_lvl5_duplicate_elements.py
> +    assert func5_duplicate_elements(c4) == {"data": ["no duplicates"]}
добавь плз проверки, они должны работать:
```python
assert func5_duplicate_elements((1,2,3)) == {"data": {}}
assert func5_duplicate_elements((1,1,1)) == {"data": {1: 3}}
assert func5_duplicate_elements("aaa") == {"data": {"a": 3}}
assert "errors" in func5_duplicate_elements([[],[]])
```

2022-01-10 12:11 UTC, alexander-sidorov commented on hw/maria_saganovich/lesson6_hw/test_lvl8_duplicate_char_number.py
> +    assert func8_duplicate_char_number([]) == {"errors": ["arg should be str"]}
добавь плз проверки, они должны работать:
```python
assert func8_duplicate_char_number("aba") == {"data": "a1b1a1"}
```

2022-01-10 12:11 UTC, alexander-sidorov commented on hw/maria_saganovich/lesson6_hw/test_lvl8_duplicate_char_number.py
> +    assert func8_duplicate_char_number("aaa777bb") == {"data": "a373b2"}
в этом случае стоит выдать ошибку, т.к. наличие цифр приводит к неоднозначному варианту

2022-01-10 12:11 UTC, alexander-sidorov commented on hw/maria_saganovich/lesson6_hw/test_lvl9_swap_keys_values.py
> +    }
добавь плз проверки, они должны работать:
```python
assert func9_swap_keys_values({}) == {"data": {}}
```

2022-01-10 20:11 UTC, maryiasa commented on hw/maria_saganovich/lesson6_hw/lvl10_empty_keys_values.py
> +def func10_empty_keys_values(arg1: Any, arg2: Any) -> dict:  # noqa: CCR001
fixed

2022-01-10 20:11 UTC, maryiasa commented on hw/maria_saganovich/lesson6_hw/lvl10_empty_keys_values.py
> +        is_error = True
fixed

2022-01-10 20:11 UTC, maryiasa commented on hw/maria_saganovich/lesson6_hw/lvl10_empty_keys_values.py
> +        if len(arg1) == 0 and len(arg2) == 0:
fixed

2022-01-10 20:12 UTC, maryiasa commented on hw/maria_saganovich/lesson6_hw/lvl12_even_keys_odd_values.py
> +def func12_even_keys_odd_values(*args: Any) -> dict:  # noqa: CCR001
fixed

2022-01-10 20:12 UTC, maryiasa commented on hw/maria_saganovich/lesson6_hw/lvl4_oldest.py
> +def func4_oldest(d1: Any) -> dict:  # noqa: CCR001
fixed

2022-01-10 20:12 UTC, maryiasa commented on hw/maria_saganovich/lesson6_hw/test_lvl2_product.py
> +    assert func2_product((1 + 2j), (3 + 4j)) == {"data": (-5 + 10j)}
checks are added

2022-01-10 20:13 UTC, maryiasa commented on hw/maria_saganovich/lesson6_hw/test_lvl5_duplicate_elements.py
> +    assert func5_duplicate_elements(c4) == {"data": ["no duplicates"]}
checks are added

2022-01-10 20:13 UTC, maryiasa commented on hw/maria_saganovich/lesson6_hw/test_lvl8_duplicate_char_number.py
> +    assert func8_duplicate_char_number([]) == {"errors": ["arg should be str"]}
done

2022-01-10 20:13 UTC, maryiasa commented on hw/maria_saganovich/lesson6_hw/test_lvl8_duplicate_char_number.py
> +    assert func8_duplicate_char_number("aaa777bb") == {"data": "a373b2"}
fixed

2022-01-10 20:13 UTC, maryiasa commented on hw/maria_saganovich/lesson6_hw/test_lvl9_swap_keys_values.py
> +    }
done

2022-01-10 20:58 UTC, alexander-sidorov requested changes

2022-01-10 20:58 UTC, alexander-sidorov commented on hw/maria_saganovich/lesson6_hw/lvl10_empty_keys_values.py
> +    if (type(arg1) != str or type(arg2) != list) and (
эта функция работает с любыми последовательностями

```python
func10_empty_keys_values("", "")
func10_empty_keys_values("", [])
func10_empty_keys_values((), [])
func10_empty_keys_values((), "")
```

как угодно
даже  `range` подойдёт

2022-01-10 20:58 UTC, alexander-sidorov commented on hw/maria_saganovich/lesson6_hw/lvl10_empty_keys_values.py
> +        return {"errors": "incorrect arg"}
почему? из двух пустых последовательностей собирается пустой словарь

2022-01-10 20:58 UTC, alexander-sidorov commented on hw/maria_saganovich/lesson6_hw/lvl10_empty_keys_values.py
> +        return {"errors": "incorrect arg"}
вроде список ошибок, а не str?

2022-01-10 20:58 UTC, alexander-sidorov commented on hw/maria_saganovich/lesson6_hw/lvl12_even_keys_odd_values.py
> +            result_error.append("should be number")
внезапно! а float, complex, bool, str, tuple, object и всё производное - нельзя? почему?

2022-01-10 20:58 UTC, alexander-sidorov commented on hw/maria_saganovich/lesson6_hw/lvl12_even_keys_odd_values.py
> +        result_data[...] = even_args[
Маш, в условиях задачи ничего такого нет

2022-01-10 20:58 UTC, alexander-sidorov commented on hw/maria_saganovich/lesson6_hw/lvl1_palindrome.py
> +        str_palindrome = str(b2).lower()
зачем строку в строку конвертировать?

2022-01-10 20:58 UTC, alexander-sidorov commented on hw/maria_saganovich/lesson6_hw/lvl2_product.py
> +        if not isinstance(arg, (int, float, complex, str, list)):
кортежи тоже можно умножать

2022-01-10 20:58 UTC, alexander-sidorov commented on hw/maria_saganovich/lesson6_hw/lvl2_product.py
> +            return {"errors": "Can't multiply sequence by non-int of types"}
список строк?

2022-01-10 20:58 UTC, alexander-sidorov commented on hw/maria_saganovich/lesson6_hw/lvl2_product.py
> +            return {"errors": "Unsupported type"}
список?

2022-01-10 21:31 UTC, alexander-sidorov requested changes
вместо тысячи комментов - добавил свои тесты)

2022-01-11 15:29 UTC, maryiasa commented
> вместо тысячи комментов - добавил свои тесты)

@alexander-sidorov можешь, пожалуйста, пересмотреть свои тесты:
test_task_02 должен же вернуться dict c ключом "data"

test_task_07:
assert func7_str_duplicate_char("aaaaaaaaaaaba") == {"data": "a11b1a1"}  #  for func8
validate_errors(func7_str_duplicate_char("aaa3"))  # for func8

test_task_08:
assert func8_duplicate_char_number("a11b1a1") == {"data": "aaaaaaaaaaaba"}  #  for func7


и еще есть вопрос насчет test_task4:
почему должно быть так?  assert func4_oldest(data) == {"data": frozenset()}
и не может быть так?  assert func4_oldest(data) == {"data": [frozenset()]}
как должно работать в случае, если у нас будет два человека с одинаковой датой?

2022-01-11 20:30 UTC, alexander-sidorov commented
@maryiasa 

моя функция validate проверяет сразу наличие правильного ключа ("data" или "errors") и если это data, то функция сразу сравнивает значение по ключу со значением из своего аргумента

с ошибками примерно так же, только я сами строки ошибок не проверяю

2022-01-11 20:32 UTC, alexander-sidorov commented
> и еще есть вопрос насчет test_task4:
> почему должно быть так? assert func4_oldest(data) == {"data": frozenset()}
> и не может быть так? assert func4_oldest(data) == {"data": [frozenset()]}
так там же только один ключ frozenset() ?
и по заданию нужно вернуть одного персонажа (каким бы его ключ-идентификатор ни был), а не список

> как должно работать в случае, если у нас будет два человека с одинаковой датой?
думаю, тут на усмотрение, или считать за ошибку, или выдать любого из одинаковых. у меня на такой кейс нету тестов)

2022-01-12 14:20 UTC, alexander-sidorov requested changes
добавил ещо тестиков)

2022-01-12 14:20 UTC, alexander-sidorov commented on hw/maria_saganovich/lesson6_hw/lvl6_dict_http_query.py
> +    if len(str(query)) > 0:
1) лишняя конверсия строки в строку
2) лишнее вычисление:

всегда меняй

```python
if len(xxx) > 0:
    ...

if len(xxx) == 0:
    ...

```

на

```python
if xxx:
    ...

if not xxx:
    ...

```

3) лишняя инструкция: `"".split()` сгенерит пустую коллекцию, и инструкция `for` (строка 12) сделает ноль телодвижений

2022-01-12 14:20 UTC, alexander-sidorov commented on hw/maria_saganovich/lesson6_hw/lvl6_dict_http_query.py
> +        data = str(query).split("&")
зачем строку в строку преобразовывать?

2022-01-12 14:20 UTC, alexander-sidorov commented on hw/maria_saganovich/lesson6_hw/lvl9_swap_keys_values.py
> +    for _value, key in enumerate(list(arg)):
зачем коллекцию в коллекцию преобразовывать?

2022-01-13 21:44 UTC, maryiasa commented on hw/maria_saganovich/lesson6_hw/lvl11_relations_bt_2_sets.py
> +    if bool(result_error):
fixed

2022-01-13 21:45 UTC, maryiasa commented on hw/maria_saganovich/lesson6_hw/lvl1_palindrome.py
> +        str_palindrome = str(palindrome)
fixed

2022-01-13 21:45 UTC, maryiasa commented on hw/maria_saganovich/lesson6_hw/lvl4_oldest.py
> +        result["data"] = sorted(result_data)
:)

2022-01-13 21:46 UTC, maryiasa commented on hw/maria_saganovich/lesson6_hw/lvl5_duplicate_elements.py
> +    if len(collection) > 0:
fixed

2022-01-13 21:48 UTC, maryiasa commented on hw/maria_saganovich/lesson6_hw/lvl6_dict_http_query.py
> +    if len(str(query)) > 0:
fixed

2022-01-13 21:48 UTC, maryiasa commented on hw/maria_saganovich/lesson6_hw/lvl6_dict_http_query.py
> +        data = str(query).split("&")
fixed

2022-01-13 21:48 UTC, maryiasa commented on hw/maria_saganovich/lesson6_hw/lvl9_swap_keys_values.py
> +    for _value, key in enumerate(list(arg)):
fixed

2022-01-14 09:41 UTC, alexander-sidorov requested changes
Маш

```python
hw/maria_saganovich/lesson6_hw/lvl2_product.py                         10      1      6      1    88%
121
hw/maria_saganovich/lesson6_hw/lvl12_even_keys_odd_values.py           20      1     14      2    91%
122
hw/maria_saganovich/lesson6_hw/lvl4_oldest.py                          19      0     12      1    97%
```

сделай coverage 100% и го мержить

2022-01-18 19:57 UTC, alexander-sidorov requested changes
вмержи себе плз main, я добавлю тестов

их нужно будет учесть и свой код пофиксить, но на дедлайн и оценку это не повлияет

однако сейчас 10 за то что на уроке добавила лямбду
и 0 за ДЗ — где декоратор?)

2022-01-20 10:03 UTC, maryiasa commented
> вмержи себе плз main, я добавлю тестов
> 
> их нужно будет учесть и свой код пофиксить, но на дедлайн и оценку это не повлияет
> 
> однако сейчас 10 за то что на уроке добавила лямбду и 0 за ДЗ — где декоратор?)

2022-01-20 10:05 UTC, maryiasa commented
> вмержи себе плз main, я добавлю тестов
> 
> их нужно будет учесть и свой код пофиксить, но на дедлайн и оценку это не повлияет
> 
> однако сейчас 10 за то что на уроке добавила лямбду и 0 за ДЗ — где декоратор?)

Я сделала, просто фиксила тесты, поэтому вовремя не запушила(
Можешь подсказать, пожалуйста, что поправить, чтобы проверка SonarCloud не падала?

2022-01-26 13:17 UTC, alexander-sidorov requested changes
активировал общие тесты, надо код для них починить)

2022-01-31 19:34 UTC, alexander-sidorov requested changes
Необходимо довести покрытие своего кода тестами до 100%

2022-02-01 15:02 UTC, alexander-sidorov approved these changes

2022-02-01 15:15 UTC, merged