Yaroslav Belaychuk - Lesson 06 HW
alexander-sidorov/tms-qap05 pull request #136
Opened 2022-01-10 10:08 UTC by YaroslavBelaychuk

2022-01-10 12:26 UTC, alexander-sidorov requested changes

2022-01-10 12:26 UTC, alexander-sidorov commented on hw/yaroslav_belaychuk/lesson006HW.py
> +        return {"TypeError"}  # type: ignore
какая тут проблема возникла с типизацией?

2022-01-10 12:26 UTC, alexander-sidorov commented on hw/yaroslav_belaychuk/lesson006HW.py
> +        return {"error"}  # type: ignore
какая проблема с типизацией тут возникла?

2022-01-10 12:26 UTC, alexander-sidorov commented on hw/yaroslav_belaychuk/lesson006HW.py
> +        return {"TypeError"}  # type: ignore
какая проблема с типизацией тут возникла?

2022-01-10 12:26 UTC, alexander-sidorov commented on hw/yaroslav_belaychuk/lesson006HW.py
> +        return {"Error"}  # type: ignore
какая проблема с типизацией тут возникла?

2022-01-10 12:26 UTC, alexander-sidorov commented on hw/yaroslav_belaychuk/test_lesson006HW.py
> +    assert zadacha_7(["a3b4c5"]) == {"TypeError"}  # type: ignore
добавь плз проверки, они должны работать:
```python
assert umnogenie(2, "a") == {"data": "aa"}
assert umnogenie(2, [2]) == {"data": [2,2]}
assert umnogenie(2, [2], 2) == {"data": [2,2,2,2]}
assert "errors" in umnogenie(2, [2], 2, [2])

assert "errors" in date_age(...)

assert "errors" in zadacha_4({})
assert "errors" in zadacha_4({1: 1j, 2: 2j})

assert "errors" in zadacha_5({})
assert "errors" in zadacha_5([])
assert "errors" in zadacha_5([[],[]])

assert zadacha_7("a11") == {"data": "aaaaaaaaaaa"}
```

2022-01-10 21:36 UTC, YaroslavBelaychuk commented on hw/yaroslav_belaychuk/test_lesson006HW.py
> +    assert zadacha_7(["a3b4c5"]) == {"TypeError"}  # type: ignore
Вроде всё поправил, надеюсь)

2022-01-10 21:52 UTC, alexander-sidorov requested changes
вместо тысячи комментов добавил тебе тесты)

2022-01-14 08:28 UTC, APOSHAml reviewed
zadacha_7("a1vf2")) == {errors : [NoDigitValue]}
 проверька вот это условие мне

2022-01-14 08:29 UTC, APOSHAml reviewed
norm

2022-01-14 16:49 UTC, APOSHAml reviewed
zadacha_4({a:date(1900,1,1), b: date(1920,1,1)})
не работает

2022-01-18 19:53 UTC, alexander-sidorov requested changes
вмержи себе main пожалуйста, и я добавлю ещё тестов

их нужно будет починить (не их, а код свой)

но на оценку и дедлайн это не повлияет

2022-01-18 19:53 UTC, alexander-sidorov commented on hw/yaroslav_belaychuk/lesson006HW.py
> +        if isinstance(func(*args, **kwargs), dict) and "errors" in func(
ты три раза вызываешь функцию тут (строки 7~12)
сократи плз до одного вызова

2022-01-18 19:53 UTC, alexander-sidorov commented on hw/yaroslav_belaychuk/lesson006HW.py
> +    return True if palindrom else False
```python
return True if True else False
```

давай отрефакторим этот код

2022-01-18 19:53 UTC, alexander-sidorov commented on hw/yaroslav_belaychuk/lesson006HW.py
> +        return {"errors": ["NonValueError"]}
недостижимый код, никогда в жизни в этой вселенной он не будет исполнен

2022-01-18 19:53 UTC, alexander-sidorov commented on hw/yaroslav_belaychuk/lesson006HW.py
> +        if isinstance(func(*args, **kwargs), dict) and "errors" in func(
UPD: 4 раза!!

2022-01-29 12:24 UTC, alexander-sidorov reviewed
Общий код и общие ошибки с @APOSHAml , так что глянь плз [его ПР и его комменты](https://github.com/alexander-sidorov/tms-qap05/pull/149)

2022-01-29 12:24 UTC, alexander-sidorov commented on hw/yaroslav_belaychuk/lesson006HW.py
> +    def wrapper(*args: Any, **kwargs: Any) -> Any:
Без `functools.wraps` твой декоратор перепишет имя, сигнатуру, документацию и аннотации каждой задекорированной функции.

2022-01-29 12:24 UTC, alexander-sidorov commented on hw/yaroslav_belaychuk/lesson006HW.py
> +        if "errors" in result:
смотри, чё будет:

```python
In [59]: p = Palindrome01(None)

In [60]: if p:
    ...:     print("lol kek")
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Input In [60], in <module>
----> 1 if p:
      2     print("lol kek")

TypeError: __bool__ should return bool, returned dict
```

2022-01-29 12:24 UTC, alexander-sidorov commented on hw/yaroslav_belaychuk/lesson006HW.py
> +        if args[0] == ("",):
поговори с @APOSHAml нащот этой строки)

2022-01-31 19:12 UTC, alexander-sidorov approved these changes

2022-01-31 19:23 UTC, alexander-sidorov requested changes
нужно покрытие своего кода довести до 100%

2022-02-01 22:12 UTC, tgrx approved these changes

2022-02-01 22:12 UTC, alexander-sidorov approved these changes

2022-02-02 08:45 UTC, merged