Siarhei Apanel - Lesson 07 HW
alexander-sidorov/tms-qap05 pull request #140
Opened 2022-01-14 21:56 UTC by APOSHAml

2022-01-17 12:22 UTC, alexander-sidorov requested changes

2022-01-17 14:12 UTC, APOSHAml commented on hw/siarhei_apanel/refakt.py
> +    return min(yer, key=lambda t: yer[t])  # type: ignore
Returning Any from function declared to
return "Union[SupportsDunderLT, SupportsDunderGT]"
        return min(yer, key=lambda t: yer[t])
                                      ^

2022-01-17 17:09 UTC, alexander-sidorov requested changes
покрытие тестами < 100%

2022-01-17 18:34 UTC, alexander-sidorov commented on hw/siarhei_apanel/refakt.py
> +    return min(yer, key=lambda t: yer[t])  # type: ignore
как насчёт тип правильно поставить вместо игнора типа? это не тот кейс, чтобы игнорить

тип нужно поставить на переменную `yer`, правильный, полный, и всё будет тип-топ

2022-01-17 18:35 UTC, alexander-sidorov approved these changes

2022-01-17 19:30 UTC, alexander-sidorov approved these changes

2022-01-18 19:44 UTC, alexander-sidorov requested changes
@APOSHAml  вмержи плз main к себе и я добавлю тестов))

они попадают, и ты сразу и оч быстро пофиксишь свой код)

на оценку и дедлайн это не повлияет

2022-01-26 12:14 UTC, alexander-sidorov requested changes
добавил общие тесты, 2 теста надо поправить

2022-01-26 16:55 UTC, closed without merging