tatsiana_kukharskaya - lesson2
alexander-sidorov/tms-qap05 pull request #26
Opened 2021-12-15 18:08 UTC by Tatsikuk26

2021-12-15 22:06 UTC, alexander-sidorov requested changes

2021-12-15 22:06 UTC, alexander-sidorov commented on hw/tatsiana_kukharskaya/test_example.py
> +
вот эту пустую строку удали плз

2021-12-15 22:06 UTC, alexander-sidorov commented on hw/tatsiana_kukharskaya/test_example.py
> +    a = 5
flake8 будет ругаться на имена, которые состоят из менее чем 3 букв.

переименуй `a` и `b` во что-нибудь типа `num1`, `num2` к примеру

2021-12-16 07:10 UTC, Tatsikuk26 commented on hw/tatsiana_kukharskaya/test_example.py
> +
done 👍

2021-12-16 07:12 UTC, Tatsikuk26 commented on hw/tatsiana_kukharskaya/test_example.py
> +    a = 5
все равно что-то падает в contributing

2021-12-16 10:06 UTC, alexander-sidorov commented on hw/tatsiana_kukharskaya/test_example.py
> +    a = 5
contributing задача проверяет только то, что в ПР присутствуют разрешённые файлы (в правильной папке `hw/...`)

2021-12-16 10:07 UTC, alexander-sidorov approved these changes
👍🏻

2021-12-16 10:17 UTC, Tatsikuk26 commented on hw/tatsiana_kukharskaya/test_example.py
> +    a = 5
понял принял)

2021-12-16 10:49 UTC, Yancharski approved these changes

2021-12-16 10:51 UTC, merged