val first commit
alexander-sidorov/tms-qap05 pull request #3
Opened 2021-12-10 19:12 UTC by lerkin011

2021-12-10 22:09 UTC, alexander-sidorov requested changes
Прошу назвать пулл-реквест так:

<Имя> <Фамилия> - Lesson 01

имя и фамилия латиницей

скобки `<` и `>` означают обязательность

---

у тебя интересная ситуация :)

твой каталог в `hw/` должен называться `valeriya_mavritskaya/` - вроде бы и просила переименовать обозначение в [validate_contributors.sh](https://github.com/alexander-sidorov/tms-qap05/blob/8616aa20bdea62c72ac090bed6594c7ffe8b5b5f/validate_contributors.sh#L46)?

придётся тебе переименовать теперь самой и сам каталог :) и закоммитить-запушить это.

2021-12-10 22:09 UTC, alexander-sidorov commented on hw/valeria_mavritskaya/test_firstone.py
> +    pass
тесты упадут тут из-за того, что после строки 2 отсутствует переход на новую строку

1. [flake8 / W391](https://www.flake8rules.com/rules/W391.html)
1. [so / What's the significance of the "No newline at end of file" log?](https://stackoverflow.com/questions/5813311/whats-the-significance-of-the-no-newline-at-end-of-file-log)
1. [so / Why should text files end with a newline?](https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline)
1. [unix.sa / What's the point in adding a new line to the end of a file?](https://unix.stackexchange.com/questions/18743/whats-the-point-in-adding-a-new-line-to-the-end-of-a-file)

2021-12-10 23:37 UTC, lerkin011 commented on hw/valeria_mavritskaya/test_firstone.py
> +    pass
1 и 2 вроде сделала.
Пока пыталась разобраться с 3м, зачем-то случайно удалила инит файл из tms-qap05/hw/. Можно у себя его просто добавить или нужно все заново начинать ((
А с 3м все равно не поняла.

2021-12-13 20:04 UTC, alexander-sidorov approved these changes
👍🏻👍🏻

2021-12-13 20:07 UTC, vadison90125 approved these changes

2021-12-13 20:42 UTC, merged