Valeriya Mavritskaya - Lesson 02
alexander-sidorov/tms-qap05 pull request #38
Opened 2021-12-15 18:52 UTC by lerkin011

2021-12-15 21:56 UTC, alexander-sidorov requested changes

2021-12-15 21:56 UTC, alexander-sidorov commented on hw/valeriya_mavritskaya/test_firstone.py
> +    assert False == 0
после нуля добавь два пробела и вот это: 

```python
# noqa: SIM300, E712
```

2021-12-15 21:56 UTC, alexander-sidorov commented on hw/valeriya_mavritskaya/test_firstone.py
> +    assert "22" == "22"
тут тоже, в конец добавь два пробела и вот это:

```python
# noqa: SIM300
```

2021-12-16 10:54 UTC, alexander-sidorov approved these changes

2021-12-16 10:58 UTC, vadison90125 approved these changes

2021-12-16 10:59 UTC, Zyola approved these changes

2021-12-16 10:59 UTC, merged