new file with code
alexander-sidorov/tms-qap05 pull request #4
Opened 2021-12-10 19:16 UTC by vadison90125

2021-12-10 22:05 UTC, alexander-sidorov requested changes
Прошу назвать пулл-реквест так:

<Имя> <Фамилия> - Lesson 01

имя и фамилия латиницей

скобки `<` и `>` означают обязательность

2021-12-10 22:05 UTC, alexander-sidorov commented on hw/vadim_maletski/test_code.py
> +print(c)
тесты падают из-за:

1. вокруг оператора присваивания `=` должны быть пробелы

    - [pep8 / Pet Peeves](https://www.python.org/dev/peps/pep-0008/#pet-peeves)

1. вокруг оператора складывания `+` должны быть пробелы

    - [pep8 / Pet Peeves](https://www.python.org/dev/peps/pep-0008/#pet-peeves)

1. после строки 4 отсутствует переход на новую строку

    1. [flake8 / W391](https://www.flake8rules.com/rules/W391.html)
    1. [so / What's the significance of the "No newline at end of file" log?](https://stackoverflow.com/questions/5813311/whats-the-significance-of-the-no-newline-at-end-of-file-log)
    1. [so / Why should text files end with a newline?](https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline)
    1. [unix.sa / What's the point in adding a new line to the end of a file?](https://unix.stackexchange.com/questions/18743/whats-the-point-in-adding-a-new-line-to-the-end-of-a-file)

2021-12-11 07:09 UTC, vadison90125 reviewed
change code in test_code.py

2021-12-11 07:39 UTC, closed without merging

2021-12-11 08:46 UTC, vadison90125 commented
reopen