Maksim-Ptitski-lesson-1
alexander-sidorov/tms-qap05 pull request #5
Opened 2021-12-10 19:18 UTC by MaksimPtitski

2021-12-10 21:59 UTC, alexander-sidorov requested changes
Прошу назвать пулл-реквест так:

<Имя> <Фамилия> - Lesson 01

имя и фамилия латиницей

скобки `<` и `>` означают обязательность

---

файл `__init__py.txt` нужно переименовать в `__init__.py`

2021-12-10 21:59 UTC, alexander-sidorov commented on hw/maksim_ptitski/test_file_01.txt
> +print('Python is great')
в нашем проекте используются двойные кавычки для текста.

потом это автоматизируется, а пока придётся поправить руками :)

[black / strings](https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html#strings)

2021-12-10 21:59 UTC, alexander-sidorov commented on hw/maksim_ptitski/test_file_01.txt
> +print('Python is great')
файл нужно переименовать из `.txt` в `.py`

2021-12-13 16:44 UTC, Yancharski approved these changes

2021-12-13 18:36 UTC, vadison90125 approved these changes

2021-12-13 21:38 UTC, tgrx approved these changes

2021-12-14 10:56 UTC, merged