Tatsiana Kukharskaya - Lesson 03
alexander-sidorov/tms-qap05 pull request #52
Opened 2021-12-17 18:53 UTC by Tatsikuk26

2021-12-17 19:59 UTC, alexander-sidorov requested changes
линтер нужно заткнуть)

2021-12-18 18:39 UTC, alexander-sidorov approved these changes

2021-12-18 19:01 UTC, SashaYaroshevich approved these changes

2021-12-18 19:11 UTC, Yancharski approved these changes

2021-12-18 19:14 UTC, merged