Kirill-Tobolich lesson 1 added 2 files
alexander-sidorov/tms-qap05 pull request #6
Opened 2021-12-10 19:19 UTC by Tobkirill

2021-12-10 21:54 UTC, alexander-sidorov requested changes
Прошу назвать пулл-реквест так:

<Имя> <Фамилия> - Lesson 01

имя и фамилия латиницей

скобки `<` и `>` означают обязательность

2021-12-10 21:54 UTC, alexander-sidorov commented on hw/kirill_tobolich/test_file1.py
> +print("Hello world")
тесты падают из-за того, что после строки 2 отсутствует переход на новую строку

1. [flake8 / W391](https://www.flake8rules.com/rules/W391.html)
1. [so / What's the significance of the "No newline at end of file" log?](https://stackoverflow.com/questions/5813311/whats-the-significance-of-the-no-newline-at-end-of-file-log)
1. [so / Why should text files end with a newline?](https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline)
1. [unix.sa / What's the point in adding a new line to the end of a file?](https://unix.stackexchange.com/questions/18743/whats-the-point-in-adding-a-new-line-to-the-end-of-a-file)

2021-12-14 15:57 UTC, MaksimPtitski approved these changes

2021-12-14 16:13 UTC, Zyola approved these changes

2021-12-14 16:18 UTC, alexander-sidorov approved these changes

2021-12-14 16:20 UTC, merged