Kirill Tobolich - Homework 03
alexander-sidorov/tms-qap05 pull request #61
Opened 2021-12-19 10:44 UTC by Tobkirill

2021-12-19 11:24 UTC, Yancharski approved these changes

2021-12-19 11:35 UTC, MaksimPtitski submitted a review, later dismissed

2021-12-19 11:36 UTC, YaroslavBelaychuk submitted a review, later dismissed

2021-12-19 12:35 UTC, MaksimPtitski submitted a review, later dismissed

2021-12-19 14:23 UTC, alexander-sidorov requested changes

2021-12-19 14:23 UTC, alexander-sidorov commented on hw/kirill_tobolich/test_hw3.py
> +        return "No solution, D < 0"  # type: ignore
Отставить возвращать строки из математических функций, особенно из полиномов))

2021-12-19 14:23 UTC, alexander-sidorov commented on hw/kirill_tobolich/test_hw3.py
> +def test_functions() -> None:
Как насчёт сделать несколько тест функций? Вон какая она у тебя громоздкая получается

2021-12-19 18:13 UTC, APOSHAml submitted a review, later dismissed

2021-12-19 23:48 UTC, alexander-sidorov approved these changes

2021-12-19 23:48 UTC, alexander-sidorov commented on hw/kirill_tobolich/test_hw3.py
> +    assert quadratic_equation(1, 1, 1) == [(-0.5 + 0.87j), (-0.5 - 0.87j)]
да!!!

2021-12-19 23:48 UTC, alexander-sidorov commented on hw/kirill_tobolich/test_hw3.py
> +    if discriminant >= 0:
очень хорошо)
но предлагаю упростить: if-ы не нужны, если ты коэффициент `a` умножишь на вещественную единицу, но типа `complex`.

2021-12-19 23:51 UTC, alexander-sidorov approved these changes

2021-12-19 23:51 UTC, alexander-sidorov commented on hw/kirill_tobolich/test_hw3.py
> +    if discriminant >= 0:
может быть, не будет `math.sqrt` работать, но тебе в помощь модуль `cmath`, или можешь корень вычислить как степень `1/2`

2021-12-20 06:42 UTC, Tatsikuk26 approved these changes

2021-12-20 10:39 UTC, Tobkirill commented on hw/kirill_tobolich/test_hw3.py
> +    if discriminant >= 0:
Если мы умножим коэфф a на complex(1), у нас все корни будут иметь вид записи комплексного числа с +0j мнимой частью. В таком случае у нас вариант просто отсекать эту мнимую часть, если она 0j, но для этого придется вводить доп.проверку на это условие. Для действительных корней более привычна запись числа не как комплексного, хотя это зависит от контекста, кто будет использовать эту функцию и в каких целях)

2021-12-20 13:12 UTC, alexander-sidorov commented on hw/kirill_tobolich/test_hw3.py
> +    if discriminant >= 0:
Всё правильно, и это не страшно. В реальном мире R является подмножеством C, то есть любое вещественное число и есть комплексное с мнимой частью 0.

2021-12-20 13:36 UTC, MaksimPtitski approved these changes

2021-12-20 13:48 UTC, merged