Vadim Maletski - Lesson 03
alexander-sidorov/tms-qap05 pull request #62
Opened 2021-12-19 15:03 UTC by vadison90125

2021-12-19 18:11 UTC, APOSHAml submitted a review, later dismissed

2021-12-19 23:45 UTC, alexander-sidorov requested changes

2021-12-19 23:45 UTC, alexander-sidorov commented on hw/vadim_maletski/test_lesson3-hw3.py
> +        x1 = None
должны быть числа)

2021-12-19 23:45 UTC, alexander-sidorov commented on hw/vadim_maletski/test_lesson3-hw3.py
> +    assert func3() is None  # type: ignore
а попробуй в функции этой не `pass`, а именно явно вернуть `None`

2021-12-19 23:45 UTC, alexander-sidorov commented on hw/vadim_maletski/test_lesson3-hw3.py
> +    assert kv_ur(1, 1, 1) == [None, None]
должны быть числа)

2021-12-20 17:00 UTC, alexander-sidorov requested changes
переименуй `hw/vadim_maletski/test_lesson3-hw3.py` плз так, чтобы им файла было валидным питоновским именем

2021-12-20 20:48 UTC, maryiasa approved these changes

2021-12-20 22:54 UTC, alexander-sidorov approved these changes

2021-12-21 07:54 UTC, Yancharski approved these changes

2021-12-21 08:03 UTC, merged