Maria Saganovich - Lesson 19 12 21
alexander-sidorov/tms-qap05 pull request #63
Opened 2021-12-19 15:26 UTC by maryiasa

2021-12-19 23:43 UTC, alexander-sidorov requested changes

2021-12-19 23:43 UTC, alexander-sidorov commented on hw/maria_saganovich/test_cat_function_saganovich.py
> +class Colors:
🙀

2021-12-19 23:43 UTC, alexander-sidorov commented on hw/maria_saganovich/test_cat_function_saganovich.py
> +        Colors.BLUE + "Enter the coefficients for the equation: " + Colors.END
так-то кайф, но я введу `1, 1, 1` и всё сломается...

2021-12-20 20:44 UTC, maryiasa commented on hw/maria_saganovich/test_cat_function_saganovich.py
> +class Colors:
сама в шоках)

2021-12-20 20:44 UTC, maryiasa commented on hw/maria_saganovich/test_cat_function_saganovich.py
> +        Colors.BLUE + "Enter the coefficients for the equation: " + Colors.END
не верю)

2021-12-20 22:53 UTC, alexander-sidorov requested changes

2021-12-20 22:53 UTC, alexander-sidorov commented on hw/maria_saganovich/test_quadratic_saganovich.py
> +def quadratic_equation() -> list:
Задача: _Написать функцию, которая вычисляет решения уравнения ax² + bx + c = 0 для коэффициентов a, b, c._

Ок, вот я вижу функцию: `quadratic_equation`.

Чтоже, я хочу её использовать, чтобы вычислить решения для a=b=0, c=10.

Как мне это сделать? Вызов `quadratic_equation(0, 0, 1)` падает с `TypeError`.

Влезть **внутрь** функции и править её код? Ну такое :) тогда уж я сам свою написал бы. То есть [повторное использование](https://ru.wikipedia.org/wiki/%D0%9F%D0%BE%D0%B2%D1%82%D0%BE%D1%80%D0%BD%D0%BE%D0%B5_%D0%B8%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5_%D0%BA%D0%BE%D0%B4%D0%B0) функции невозможно.

Ладно, яжпрограммист, могу и переписать код. 

Вижу ниже список с заготовленными значениями. Супер! Добавляю туда вот это:

```
[1, 1, 1],
[0, 1, 1],
[0, 0, 1]
```

И функция для варианта `[1, 1, 1]` возвращает `[[True]]`. Это что? Ответ на математическое уравнение — "да" ? ))

А `[0, 1, 1]` — это "нет" :)

А `[0, 0, 1]` вообще падает с `ZeroDivisionError`.

Поэтому предлагаю или доработать функцию так, чтобы она была функцией (3 входа и 1 выход), и, по условию задачи, всегда давала ответ для любых чисел, и всегда два корня, и т.к. это мат.уравнение, то и результаты должны быть математические, ни "да/нет", ни строки, ни какое-то ещё спецзаглушки не подходят)

или пока что отложить её до следующего раза, не в этом ПР

2021-12-20 22:53 UTC, alexander-sidorov commented on hw/maria_saganovich/test_functions_saganovich.py
> +    assert func4() == [-5, -99]
ДЗ: _Написать функцию, которая возвращает число меньше нуля._

`func4` возвращает список

2021-12-20 22:53 UTC, alexander-sidorov commented on hw/maria_saganovich/test_functions_saganovich.py
> +    assert func5() == [""]
ДЗ: _Написать функцию, которая возвращает пустую строку._

`func5` возвращает список

2021-12-21 05:04 UTC, Tatsikuk26 submitted a review, later dismissed

2021-12-21 07:21 UTC, maryiasa commented on hw/maria_saganovich/test_functions_saganovich.py
> +    assert func4() == [-5, -99]
done

2021-12-21 07:21 UTC, maryiasa commented on hw/maria_saganovich/test_functions_saganovich.py
> +    assert func5() == [""]
done

2021-12-21 07:25 UTC, maryiasa commented on hw/maria_saganovich/test_quadratic_saganovich.py
> +def quadratic_equation() -> list:
[0, 1, 1] - нет, потому что а должна быть != 0
[1, 1, 1] с этим согласна, не хватало проверки
quadratic_function не может возвращать только два корня, потому что в зависимости от дискриминанта, она должна возвращаться либо 2 корня, либо один, либо нету корней, когда нету корней возвращает фолс.
Я удалила этот код, подумаю на досуге

2021-12-21 07:37 UTC, denisasipenko approved these changes

2021-12-21 07:41 UTC, alexander-sidorov approved these changes

2021-12-21 07:44 UTC, Tatsikuk26 approved these changes

2021-12-21 07:47 UTC, merged