Siarhei Apanel - Lesson 03
alexander-sidorov/tms-qap05 pull request #64
Opened 2021-12-19 16:50 UTC by APOSHAml

2021-12-19 23:42 UTC, alexander-sidorov requested changes

2021-12-19 23:42 UTC, alexander-sidorov commented on hw/siarhei_apanel/test_hw.py
> +    assert func(1, 2, 1) == [-1.0]
должно быть ровно 2 корня :)
и должно работать на коэффициентах `(1,1,1)`

2021-12-20 10:24 UTC, alexander-sidorov requested changes

2021-12-20 10:24 UTC, alexander-sidorov commented on hw/siarhei_apanel/test_hw.py
> +        return [None, None]
Внезапно!

2021-12-20 16:56 UTC, alexander-sidorov submitted a review, later dismissed

2021-12-20 16:56 UTC, alexander-sidorov commented on hw/siarhei_apanel/test_hw.py
> +        x1 = (-back + sqrt) / 2 * a1
чем строки `10~13` отличаются от `6~8` ?

2021-12-20 17:13 UTC, MaksimPtitski approved these changes

2021-12-21 00:59 UTC, alexander-sidorov approved these changes

2021-12-21 06:23 UTC, vadison90125 approved these changes

2021-12-21 09:02 UTC, maryiasa approved these changes

2021-12-21 09:06 UTC, denisasipenko approved these changes

2021-12-21 09:09 UTC, merged