denismaster
alexander-sidorov/tms-qap05 pull request #7
Opened 2021-12-10 19:21 UTC by denisasipenko

2021-12-10 21:47 UTC, alexander-sidorov requested changes
Прошу назвать пулл-реквест так:

<Имя> <Фамилия> - Lesson 01

имя и фамилия латиницей

скобки `<` и `>` означают обязательность

2021-12-10 21:47 UTC, alexander-sidorov commented on hw/denis_asipenko/test_ADA1.py
> +    assert True, "not True"
тесты падают из-за того, что после строки 2 отсутствует переход на новую строку

1. [flake8 / W391](https://www.flake8rules.com/rules/W391.html)
1. [so / What's the significance of the "No newline at end of file" log?](https://stackoverflow.com/questions/5813311/whats-the-significance-of-the-no-newline-at-end-of-file-log)
1. [so / Why should text files end with a newline?](https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline)
1. [unix.sa / What's the point in adding a new line to the end of a file?](https://unix.stackexchange.com/questions/18743/whats-the-point-in-adding-a-new-line-to-the-end-of-a-file)

2021-12-14 09:43 UTC, alexander-sidorov approved these changes
👍🏻👍🏻

2021-12-14 09:45 UTC, vadison90125 approved these changes

2021-12-14 09:52 UTC, merged