Tatsiana Kukharskaya - Lesson 04
alexander-sidorov/tms-qap05 pull request #76
Opened 2021-12-22 18:47 UTC by Tatsikuk26

2021-12-22 19:58 UTC, alexander-sidorov approved these changes

2021-12-24 07:25 UTC, vadison90125 approved these changes

2021-12-24 17:50 UTC, maryiasa approved these changes

2021-12-29 09:30 UTC, alexander-sidorov requested changes

2021-12-29 09:30 UTC, alexander-sidorov commented on hw/tatsiana_kukharskaya/test_hw3.py
> +from hw.tatsiana_kukharskaya.hw3 import avr1, avr2, den, k, kim
при активном виртуальном окружении

```bash
make format
```

2022-02-02 18:43 UTC, closed without merging