add new files
alexander-sidorov/tms-qap05 pull request #8
Opened 2021-12-10 19:22 UTC by SashaYaroshevich

2021-12-10 21:35 UTC, alexander-sidorov requested changes
Прошу назвать пулл-реквест так:

<Имя> <Фамилия> - Lesson 01

имя и фамилия латиницей

скобки `<` и `>` означают обязательность

2021-12-10 21:35 UTC, alexander-sidorov commented on hw/sasha_yaroshevich/test_chtoto.py
> +    assert True, "not True"
тесты падают из-за того, что тут две пустых строки в файле, а надо бы чтобы была ровно одна:

[Flake8 / W391](https://www.flake8rules.com/rules/W391.html)

2021-12-10 21:41 UTC, alexander-sidorov requested changes
Прошу назвать пулл-реквест так:

<Имя> <Фамилия> - Lesson 01

имя и фамилия латиницей

скобки `<` и `>` означают обязательность

2021-12-13 20:18 UTC, alexander-sidorov approved these changes
👍🏻

2021-12-13 20:20 UTC, vadison90125 approved these changes

2021-12-14 06:48 UTC, Zyola approved these changes

2021-12-14 06:52 UTC, merged