Andrei Bondar - Lesson 4
alexander-sidorov/tms-qap05 pull request #81
Opened 2021-12-22 19:02 UTC by Andrei9325

2021-12-22 20:00 UTC, alexander-sidorov requested changes

2021-12-22 20:00 UTC, alexander-sidorov commented on hw/andrei_bondar/test_bondar3hw.py
> +from hw.andrei_bondar.test_bondar32hw import a
переименуй файл `test_bondar32hw.py` так, чтобы он не был тестом (не `test_`)

2021-12-23 09:41 UTC, alexander-sidorov approved these changes

2021-12-23 11:13 UTC, Tobkirill approved these changes

2021-12-24 06:39 UTC, vadison90125 approved these changes

2021-12-24 06:45 UTC, Zyola approved these changes

2021-12-24 06:52 UTC, merged