Yaroslav Belaychuk - Lesson 04
alexander-sidorov/tms-qap05 pull request #87
Opened 2021-12-22 19:19 UTC by YaroslavBelaychuk

2021-12-22 19:55 UTC, APOSHAml approved these changes

2021-12-22 19:57 UTC, alexander-sidorov requested changes

2021-12-22 19:57 UTC, alexander-sidorov commented on hw/yaroslav_belaychuk/test_yarik04.py
> +from hw.yaroslav_belaychuk.test_yarikhw import fnc
файл `test_yarikhw` переименуй так, чтобы он не был тестом (не `test_`)

2021-12-24 09:01 UTC, alexander-sidorov requested changes

2021-12-24 09:01 UTC, alexander-sidorov commented on hw/yaroslav_belaychuk/Test_Yarik.py
> -    assert True, "not True"
И вообще тест пустой

2021-12-24 09:01 UTC, alexander-sidorov commented on hw/yaroslav_belaychuk/yarik104.py
> +def test_f() -> None:
Тест функция в обычном модуле не будет запускаться

2021-12-24 09:01 UTC, alexander-sidorov commented on hw/yaroslav_belaychuk/yarikhw.py
> +    assert fnc(1, 2, 1) == [-2.0, -2.0]
Проверки внутри обычного модуля смысла не несут

2021-12-24 16:10 UTC, closed without merging