Andrey Yelin - Lesson 04
alexander-sidorov/tms-qap05 pull request #88
Opened 2021-12-22 19:34 UTC by Zyola

2021-12-22 19:49 UTC, alexander-sidorov requested changes
надо добавить `test_` файл с тестом для `example()`

2021-12-24 06:46 UTC, vadison90125 approved these changes

2021-12-24 06:47 UTC, Tatsikuk26 approved these changes

2021-12-24 06:48 UTC, Andrei9325 approved these changes

2021-12-24 08:56 UTC, alexander-sidorov approved these changes

2021-12-24 13:56 UTC, merged