Vadim Maletski - Lesson 04 hw4
alexander-sidorov/tms-qap05 pull request #89
Opened 2021-12-23 12:42 UTC by vadison90125

2021-12-23 12:58 UTC, alexander-sidorov requested changes
А вообще что это за Дз?

2021-12-23 12:58 UTC, alexander-sidorov commented on hw/vadim_maletski/test_hw4test.py
> +from hw.vadim_maletski.test_hw4func import func_answer
Модуль с тестируемой функцией переназови плз, чтобы он на `test_` не начинался

2021-12-23 13:20 UTC, alexander-sidorov approved these changes
А что это за дз?

2021-12-23 13:33 UTC, Tobkirill submitted a review, later dismissed

2021-12-23 13:34 UTC, MaksimPtitski submitted a review, later dismissed

2021-12-23 13:40 UTC, Zyola approved these changes

2021-12-23 14:16 UTC, Yancharski submitted a review, later dismissed

2021-12-23 15:17 UTC, alexander-sidorov requested changes
```python
func() == 0 or 1
```

превращается в

```python
(func() == 0) or 1
```

что всегда истинно

2021-12-23 19:17 UTC, alexander-sidorov requested changes

2021-12-23 19:17 UTC, alexander-sidorov commented on hw/vadim_maletski/test_hw4test.py
> +    assert func_answer("Нет") == "А могли бы знать"
[вот покрытие твоего кода](https://github.com/alexander-sidorov/tms-qap05/runs/4619825035?check_suite_focus=true#step:7:128) этим тестом:

```
----------- coverage: platform linux, python 3.9.9-final-0 -----------
Name                                               Stmts   Miss Branch BrPart  Cover
------------------------------------------------------------------------------------
hw/vadim_maletski/func.py                              5      0      4      1    89%
```

89%, 1 ветвь не покрыта, подсказать в чём дело или сам разберёшься?

2021-12-23 20:32 UTC, alexander-sidorov approved these changes

2021-12-24 06:49 UTC, Tatsikuk26 approved these changes

2021-12-24 07:02 UTC, Andrei9325 approved these changes

2021-12-24 07:02 UTC, Zyola approved these changes

2021-12-24 07:15 UTC, merged