sadls
alexander-sidorov/tms-qap05 pull request #9
Opened 2021-12-10 19:25 UTC by Andrei9325

2021-12-10 21:30 UTC, alexander-sidorov requested changes
файл `test_ABN.py` нужно вообще удалить.

так как он уже в Гите, его нужно удалить командой `git rm` [справка](https://git-scm.com/docs/git-rm)

2021-12-10 21:30 UTC, alexander-sidorov commented on hw/andrei_bondar/__init__.py
> +    assert True, "not True"
тесты упадут, потому что после строки 2 должна идти одна пустая строка.

[Flake8 / W391](https://www.flake8rules.com/rules/W391.html)

2021-12-10 21:33 UTC, alexander-sidorov requested changes
Прошу назвать пулл-реквест так:

<Имя> <Фамилия> - Lesson 01

имя и фамилия латиницей

скобки `<` и `>` означают обязательность

2021-12-10 21:33 UTC, alexander-sidorov commented on hw/andrei_bondar/__init__.py
> +    assert True, "not True"
более того, этот код должен быть в `test_*.py` файле.

`__init__.py` сейчас должен быть пустым

2021-12-10 21:44 UTC, alexander-sidorov requested changes

2021-12-10 21:44 UTC, alexander-sidorov commented on hw/andrei_bondar/__init__.py
> +    assert True, "not True"
тесты падают из-за того, что после строки 2 отсутствует переход на новую строку

1. [flake8 / W391](https://www.flake8rules.com/rules/W391.html)
1. [so / What's the significance of the "No newline at end of file" log?](https://stackoverflow.com/questions/5813311/whats-the-significance-of-the-no-newline-at-end-of-file-log)
1. [so / Why should text files end with a newline?](https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline)
1. [unix.sa / What's the point in adding a new line to the end of a file?](https://unix.stackexchange.com/questions/18743/whats-the-point-in-adding-a-new-line-to-the-end-of-a-file)

2021-12-10 21:45 UTC, alexander-sidorov requested changes

2021-12-10 21:45 UTC, alexander-sidorov commented on hw/andrei_bondar/__init__.py
> +    assert True, "not True"
тесты падают из-за того, что после строки 2 отсутствует переход на новую строку

1. [flake8 / W391](https://www.flake8rules.com/rules/W391.html)
1. [so / What's the significance of the "No newline at end of file" log?](https://stackoverflow.com/questions/5813311/whats-the-significance-of-the-no-newline-at-end-of-file-log)
1. [so / Why should text files end with a newline?](https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline)
1. [unix.sa / What's the point in adding a new line to the end of a file?](https://unix.stackexchange.com/questions/18743/whats-the-point-in-adding-a-new-line-to-the-end-of-a-file)

2021-12-14 09:42 UTC, alexander-sidorov requested changes

2021-12-14 09:42 UTC, alexander-sidorov commented on hw/andrei_bondar/test_bondar.py
> +   утверждать Истинно , «не Истинно»
Это не будет работать )

2021-12-14 09:42 UTC, alexander-sidorov commented on test_ABN.py
> +def test_example() -> None:
Этот файл лежит вне твоей рабочей папки

2021-12-14 11:00 UTC, alexander-sidorov approved these changes

2021-12-14 12:17 UTC, denisasipenko approved these changes

2021-12-14 12:25 UTC, vadison90125 approved these changes

2021-12-14 12:37 UTC, merged