Siarhei Apanel - Lesson 04 HW
alexander-sidorov/tms-qap05 pull request #91
Opened 2021-12-23 18:07 UTC by APOSHAml

2021-12-23 19:14 UTC, alexander-sidorov requested changes

2021-12-23 19:14 UTC, alexander-sidorov commented on hw/siarhei_apanel/refakt.py
> +def vopros(question: str, self: str) -> str:
`question` тут зачем?

2021-12-23 19:14 UTC, alexander-sidorov commented on hw/siarhei_apanel/refakt.py
> +        return "Несоответствующее значение"
о а вот за это респек! 👍🏻

2021-12-23 19:14 UTC, alexander-sidorov commented on hw/siarhei_apanel/test_HW2.py
> +# Выбирете ответ на предложенный вопрос и вызовете фунцию
а можешь этот комментарий с русского языка перевести на питоновский? )

2021-12-23 19:14 UTC, alexander-sidorov commented on hw/siarhei_apanel/test_HW2.py
> +    assert vopros(question, answerNO) == "А могли бы и знать!"
а где проверка случая `else`? :)

вот инфа из билд лога:

```
----------- coverage: platform linux, python 3.9.9-final-0 -----------
Name                                               Stmts   Miss Branch BrPart  Cover
------------------------------------------------------------------------------------
hw/siarhei_apanel/refakt.py                           16      1      4      1    90%
------------------------------------------------------------------------------------
TOTAL                                                520     28     10      1    95%
```

[вот тут](https://github.com/alexander-sidorov/tms-qap05/runs/4620806132?check_suite_focus=true#step:7:129) посмотри плз

2021-12-23 19:14 UTC, alexander-sidorov commented on hw/siarhei_apanel/test_HW2.py
> +    assert vopros(question, answerNO) == "А могли бы и знать!"
имею в виду то, что покрытие твоего кода 90% — потому что случай с `else` не потестировал

2021-12-23 19:14 UTC, alexander-sidorov commented on hw/siarhei_apanel/refakt.py
> +def vopros(question: str, self: str) -> str:
`self` в некотором смысле "зарезервированное" имя, попрошу его переименовать

2021-12-23 21:55 UTC, alexander-sidorov approved these changes

2021-12-24 07:23 UTC, vadison90125 approved these changes

2021-12-24 07:40 UTC, maryiasa approved these changes

2021-12-24 08:17 UTC, merged