Maria Saganovich - Lesson 04 hw
alexander-sidorov/tms-qap05 pull request #94
Opened 2021-12-24 14:21 UTC by maryiasa

2021-12-25 13:46 UTC, alexander-sidorov requested changes

2021-12-25 13:46 UTC, alexander-sidorov commented on hw/maria_saganovich/quadratic_equation.py
> +    if a1 == 0:
всё-таки `a` может быть `0`, просто уравнение превращается в линейное и решается изи)

2021-12-25 13:46 UTC, alexander-sidorov commented on hw/maria_saganovich/quadratic_equation.py
> +    print("Discriminant: D = %.1f" % discriminant)  # noqa: S001, MOD001, T001
используй f-строки плз :) 

```python
value = 123.45
text = f"value = {value:.1f}"
print(text)
```

2021-12-25 13:46 UTC, alexander-sidorov commented on hw/maria_saganovich/quadratic_equation.py
> +    else:
если дискриминант < 0, то это не страшно:

```
x² + 2x + 2 = 0

D = 2² – 4·1·2 = 4 – 8 = –4
√D = √(–4) = √[4 · (–1)] = √4 · √(–1) = 2 · √(–1)
```

сделаем замену вот такую, чтобы меньше писать: `j = √(–1)`

получим:

```
√D = 2 · √(–1) = 2·j
```

и всё прекрасно считается!

```
x₁ = (–b + √D) / 2·a = (–2 + 2j) / 2 = –1 + 1j
x₂ = (–b – √D) / 2·a = (–2 – 2j) / 2 = –1 – 1j
```

вот эти значения можешь загрузить в Python и убедиться, что всё работает:
![image](https://user-images.githubusercontent.com/76160017/147386181-05aace71-f34e-421b-ad27-559be67956e4.png)

единственный вариант, когда корней ну точно никаких нет, это когда `a=0, b=0, c≠0`:

```
0·x² + 0·x + 1 = 0
=>
1 = 0
```
что невозможно ни при каких `x`.

но и это можно обойти тем, что в Python есть "не-число": not-a-number, или "nan"

```python
x1 = x2 = float("nan")
```

а так как мы оперируем комплексными числами — которые в форме `u + w·j` — то можем сразу использовать

```python
complex("nan")
```

и таким образом уравнение в python всегда будет давать результат, всегда два корня и всегда типа `complex`.

попробуй)

2021-12-26 15:48 UTC, maryiasa commented on hw/maria_saganovich/quadratic_equation.py
> +def quadratic_equation() -> Any:
я попробую)

2022-02-02 18:43 UTC, closed without merging