Andrey Yelin - Lesson 05
alexander-sidorov/tms-qap05 pull request #98
Opened 2021-12-24 17:34 UTC by Zyola

2021-12-24 20:12 UTC, APOSHAml submitted a review, later dismissed

2021-12-25 12:52 UTC, alexander-sidorov requested changes

2021-12-25 12:52 UTC, alexander-sidorov commented on hw/andrey_yelin/test_lesson05.py
> +if __name__ == "__main__":
вот это надо в модуль с логикой вынести, не в тест

2021-12-25 17:08 UTC, alexander-sidorov requested changes

2021-12-25 17:08 UTC, alexander-sidorov commented on hw/andrey_yelin/test_lesson05.py
> +    assert aggression(True) == "оно и видно"
случай, когда аргумент `False`, тоже надо протестировать, иначе мы не можем гарантировать, что этот вариант работает правильно

2021-12-25 17:23 UTC, Zyola commented on hw/andrey_yelin/test_lesson05.py
> +    assert aggression(True) == "оно и видно"
Add the "False" argument to the test

2021-12-26 01:51 UTC, alexander-sidorov approved these changes

2021-12-26 12:14 UTC, MaksimPtitski approved these changes

2021-12-26 12:15 UTC, APOSHAml approved these changes

2021-12-26 15:11 UTC, merged