Yaroslav Belaychuk - Lesson05
alexander-sidorov/tms-qap05 pull request #99
Opened 2021-12-24 17:35 UTC by YaroslavBelaychuk

2021-12-24 20:12 UTC, APOSHAml submitted a review, later dismissed

2021-12-25 12:51 UTC, alexander-sidorov requested changes

2021-12-25 12:51 UTC, alexander-sidorov commented on hw/yaroslav_belaychuk/test_lesson5.py
> +def aggression(know: bool) -> str:
вынеси логику в отдельный модуль, не в тестовый

2021-12-25 12:51 UTC, alexander-sidorov commented on hw/yaroslav_belaychuk/test_lesson5.py
> +if __name__ == "__main__":
это тоже в отдельный модуль, в тот же, где и логика `aggression` будет

2021-12-26 15:58 UTC, APOSHAml reviewed
Поставь пробел в пул реквест между лессон и 05

2021-12-26 18:50 UTC, APOSHAml approved these changes

2021-12-26 19:00 UTC, vadison90125 approved these changes

2021-12-26 19:39 UTC, alexander-sidorov approved these changes

2021-12-26 22:33 UTC, merged